#!/bin/bash

#### sublime-text-2
sudo add-apt-repository -y ppa:webupd8team/sublime-text-2
#necessary / real
sudo sed -i 's/artful/zesty/g' /etc/apt/sources.list.d/*.list
sudo apt-fast -y update
sudo apt-fast -y install sublime-text