#!/bin/bash
########configurations

###################################################Install the latest stable kernel v3.15.6
#wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v3.15.6-utopic/linux-headers-3.15.6-031506_3.15.6-031506.201407172034_all.deb

#wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v3.15.6-utopic/linux-headers-3.15.6-031506-generic_3.15.6-031506.201407172034_amd64.deb

#wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v3.15.6-utopic/linux-image-3.15.6-031506-generic_3.15.6-031506.201407172034_amd64.deb

#sudo dpkg -i linux-headers-3.15*.deb linux-image-3.15*.deb

###################################################Disable guest account & remote login - http://robersoft.blogcindario.com/2011/10/00036-deshabilitar-la-cuenta-de-invitado-en-ubuntu-11-10-oneiric-ocelot.html - http://linux-hispano.blogspot.com.es/2013/10/eliminar-cuenta-invitado-e-inicio-de.html
#sudo sh -c 'echo "

#allow-guest=false
#greeter-show-remote-login=false

#" >> /etc/lightdm/lightdm.conf.d/50-unity-greeter.conf'

###################################################Disable wireless & bluetooth on startup
#sudo sh -c 'echo "

#rfkill block bluetooth
#rfkill block wifi

#" >> /etc/rc.local'

###################################################Less brightness ####WORKING
#sudo sh -c 'echo "

#" >> /xxx'
