#!/bin/bash
########configurations

###################################################Disable guest account & remote login - http://robersoft.blogcindario.com/2011/10/00036-deshabilitar-la-cuenta-de-invitado-en-ubuntu-11-10-oneiric-ocelot.html - http://linux-hispano.blogspot.com.es/2013/10/eliminar-cuenta-invitado-e-inicio-de.html
#sudo sh -c 'echo "

#allow-guest=false
#greeter-show-remote-login=false

#" >> /etc/lightdm/lightdm.conf.d/50-unity-greeter.conf'

###################################################Disable wireless & bluetooth on startup
#sudo sh -c 'echo "

#rfkill block bluetooth
#rfkill block wifi

#" >> /etc/rc.local'

###################################################Less brightness ####WORKING
#sudo sh -c 'echo "

#" >> /xxx'
