#!/bin/bash
########installpackages

sudo apt-get -y update
sudo apt-get -y upgrade

####Backup & Sync
#sudo apt-get -y install gparted backintime-gnome sbackup-plugins-fuse grsync timeshift grive-toolsxsane syncdrive
#wget http://downloads.sourceforge.net/project/directorysync/DirSync%20Pro%20%28stable%29/1.49/DirSyncPro-1.49-Linux.zip

####OS & Utilities
#sudo apt-get -y install checkbox-qt - SYSTEM TESTING APP
#sudo apt-get -y install hplip winusb indicator-netspeed i-nex
#sudo apt-get -y install laptop-mode-tools - gksu lmt-config-gui - This to launch it
#sudo apt-get -y install libfile-mimeinfo-perl catfish bleachbit
#sudo apt-get -y install qtnx unetbootin usb-imagewriter gddrescue testdisk variety baobab gsmartcontrol calendar-indicator
#sudo apt-get -y install xscreensaver-gl xscreensaver-gl-extra
#sudo apt-get -y install alarm-clock gmrun jupiter lm-sensors psensor conky conky-manager tmux xbindkeys xbindkeys-config htop pcmanfm
#sudo apt-get -y install hplip-gui
#sudo apt-get -y install voice-commands

########Desktop Environment
##gnome-session-fallback
#sudo apt-get -y install gnome-session-fallback
##lxqt - http://entornosgnulinux.com/2014/05/16/i-lxqt-0-7-0-en-ubuntu-14-04-lts-trusty-configuracion-qt/
#sudo apt-get -y install lxqt-metapackage lxqt-panel gtk2-engines-qtcurve pcmanfm kdelibs5-plugins lxappearance lxappearance-obconf openbox
##cinnamon
#sudo apt-get -y install cinnamon
##mate (1)
#sudo apt-get -y install mate-desktop-environment
#mate (2) - http://wiki.mate-desktop.org/download - http://wiki.mate-desktop.org/replace_unity_by_mate
#sudo apt-get install --no-install-recommends mate-desktop-environment mate-desktop-environment-extra caja-gksu caja-sendto mate-indicator-applet mate-icon-theme-faenza
#sudo apt-get install mate-notification-daemon mate-media-pulse mate-system-tools mate-system-tools-common mate-system-monitor-common
#sudo apt-get install ambiance-colors radiance-colors
#sudo apt-get remove gcalctool gnome-screenshot gedit file-roller eog gnome-system-monitor gnome-system-log baobab gnome-terminal gnome-applets gnome-media gnome-power-manager gnome-screensaver
#sudo apt-get remove gnome-calculator evince

##e17
#sudo apt-get -y install e17

########Themes
##ambiance-grey
#sudo apt-get -y install ambiance-grey

####Language packages
#sudo apt-get -y install myspell-es wspanish language-pack-es language-pack-es-base 
#sudo apt-get -y install myspell-en-gb myspell-en-us
#sudo apt-get -y install aspell aspell-en aspell-es

####Security & Privacy
#sudo apt-get -y install seahorse tor-browser

####CD/DVD Tools
#sudo apt-get -y install furiusisomount devede isomaster k3b acetoneiso 

####Photos & Graphics
#sudo apt-get -y install shotwell gthumb photo xnviewmp
#sudo apt-get -y install inkscape scribus gwenview

####Audio & Music
#sudo apt-get -y install sound-juicer audacity mixxx spotify-client

####Videos & Movies
#sudo apt-get -y install kazam openshot pitivi cinelerra-cv popcorn-time
#sudo apt-get -y install kdenlive - CAREFULL, a lot of kde packages

####All multimedia content
##pepper-flash-player from official repos, ONLY FOR 14.04 - http://www.webupd8.org/2014/01/pepper-flash-player-installer-for.html
#sudo apt-get -y install pepperflashplugin-nonfree
#sudo update-pepperflashplugin-nonfree --install
#sudo update-pepperflashplugin-nonfree --uninstall - TO UNINSTALL

##pepper-flash-player ancient from ppa for older Ubuntu versions - http://www.webupd8.org/2013/04/install-pepper-flash-player-for.html
#sudo apt-get -y install pepflashplugin-installer
#sudo sh -c 'echo ". /usr/lib/pepflashplugin-installer/pepflashplayer.sh" >> /etc/chromium-browser/default'

##best performance on flash - http://blog.timvalenta.com/2013/01/chromes-fullscreen-flash-performance-is-slow-laggy-and-heartwrenching/

#sudo apt-get -y install non-free-codecs libxine1-ffmpeg gxine mencoder libmpcdec6 libquicktime2 flac faac faad sox ffmpeg2theora libmpeg2-4 uudeview libmpeg3-1 mpeg3-utils mpegdemux liba52-0.7.4-dev mpeg2dec vorbis-tools id3v2 mpg321 mpg123 libflac++6 ffmpeg libmp4v2-2 icedax tagtool easytag id3tool lame libmad0 libjpeg-progs
#sudo apt-get -y install gstreamer0.10-ffmpeg gstreamer0.10-fluendo-mp3 gstreamer0.10-gnonlin gstreamer0.10-plugins-bad-multiverse totem gstreamer-dbus-media-service gstreamer-tools
#sudo apt-get -y install gsfonts gsfonts-x11 ttf-liberation ttf-droid ttf-dejavu libdvdcss2 w64codecs

####Development
#sudo apt-get -y install atom meld vim sublime-text-3
#sudo apt-get -y install kicad
#sudo apt-get -y install notepad-qml qtcreator #### Dependencies problem, be careful.
#sudo apt-get -y install wine1.7 playonlinux
#sudo apt-get -y install mono-complete mono-basic-dbg

##openjdk6
#sudo apt-get -y install openjdk-6-jre openjdk-6-jdk icedtea-6-plugin

##openjdk7
#sudo apt-get -y install openjdk-7-jre openjdk-7-jdk icedtea-7-plugin

##openjdk8
#sudo apt-get -y install openjdk-8-jre openjdk-8-jdk icedtea-8-plugin

##Oracle Java6
#sudo apt-get -y install oracle-java6-installer
#sudo apt-get install oracle-java6-set-default

##Oracle Java7
#sudo echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
#sudo apt-get -y install oracle-java7-installer
#sudo update-java-alternatives -s java-7-oracle
#sudo apt-get install oracle-java7-set-default

##Oracle Java8
#sudo echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
#sudo apt-get -y install oracle-java8-installer
#sudo update-java-alternatives -s java-8-oracle
#sudo apt-get install oracle-java8-set-default

####Web Browsers
#sudo apt-get -y install chromium-browser

####Social
#sudo apt-get -y install choqok hotot xchat pidgin-plugin-pack pidgin-twitter pidgin-libnotify pidgin-guifications 
#skype - FROM WEB OR http://www.noobslab.com/2014/01/skype-released-new-version-install-in.html

####File Management
#sudo apt-get -y install lha #### unable to locate on 14.04
#sudo apt-get -y install filezilla
#sudo apt-get -y install spacefm mc
##Thunar
#sudo apt-get -y install thunar thunar-data thunar-volman libthunarx-2-0 thunar-archive-plugin thunar-media-tags-plugin ffmpegthumbnailer
#sudo apt-get -y install xfce4-goodies

####File Sharing
#sudo apt-get -y install amule deluge axel

####News & Books
#sudo apt-get -y install gpodder calibre newsbeuter rssowl quiterss

####Office & Productivity
#sudo apt-get -y install okular evince lyx rednotebook zim txt2tags poppler-utils pdftk

####Games
#sudo apt-get -y install steam steam-login
#sudo apt-get -y install 0ad true-combat-elite americas-army:i386 lincity-ng crossover-games crossover-pro gamedevelop djl ogs-mahjong ogs-mahjong-music-addon sandboxgamemaker opencity teeworlds d2x-rebirth-full d2x-xl-executable numptyphysics violetland kolf neverputt maximinigolf assaultcube sorr iconqueru hedgewars

####Extra

##Upgrading system
#sudo apt-get -y upgrade

##Wine example
#wget http://dl.desktop.line.naver.jp/naver/LINE/win/LineInst.exe
#wine LineInst.exe

##Repairing jdownloader v1 if is necessary
#sudo update-alternatives --config java

#### TO INSTALL MANUALLY

#http://www.opera.com/download/guide/?os=linux

#http://labs.sialan.org/projects/sigram

#http://www.time4popcorn.eu/

##ONLY FOR UBUNTU WITH UNITY SURELY

sudo apt-get -y install ubuntu-tweak unity-tweak-tool classicmenu-indicator
#sudo apt-get -y install appgrid unsettings indicator-multiload indicator-cpufreq my-weather-indicator 
#sudo apt-get -y install diodon diodon-plugins

#### ONLY FOR KUBUNTU

#sudo apt-get -y install muon

########installpackagesproblematic

####General packages
#sudo apt-get -y install unity-reboot
#sudo apt-get -y install acroread-common acroread acroread-fonts
#sudo apt-get -y install aptoncd multisystem remastersys remastersys-gui ubiquity-frontend-gtk ubiquity-slideshow-lubuntu bootchart 
#sudo apt-get -y install blender gadmin-rsync mate-core
#sudo apt-get -y install mounty ddrescue  #### NEED TO ADD PPA
#sudo apt-get -y install eog eog-plugins

####Compiz + Cairo-dock + Emerald
sudo apt-get -y install compizconfig-settings-manager compiz fusion-icon compiz-plugins
sudo apt-get -y install cairo-dock cairo-dock-plug-ins-data cairo-dock-plug-ins cairo-dock-data cairo-dock-core cairo-dock-plug-ins-integration cairo-dock-plug-ins-dbus-interface-python libgldi3
sudo apt-get -y install dockbarx docky plank gnome-do
#sudo apt-get -y install avant-window-navigator - not for 14.04

#sudo apt-get -y install emerald 
#sudo apt-get -y install metacity

####Not free codecs
#sudo apt-get -y install nautilus-script-audio-convert flashplugin-nonfree-extrasound:i386 icedtea-plugin w32codecs

####ERROR
#sudo apt-get -y install quickly quickly-widgets
#sudo apt-get -y install python-snippets acire libvte-2.90-dev libvte-dev python-vte desktopcouch  #### ERROR

####PROBLEMS
#sudo apt-get -y install cairo-compmgr cairo-compmgr-plugins  #### POSSIBLY DEPENDENCIES ERROR
#sudo apt-get -y install mountmanager ntfsprogs  #### ERROR
#sudo apt-get -y install wally wallch

####DISCONTINUED
#sudo apt-get -y install app-install-data-medibuntu apport-hooks-medibuntu	#### DISCONTINUED

########uninstallpackages

####Possibly needless programs
#sudo apt-get -y remove openjdk-6-jre openjdk-6-jdk icedtea-6-plugin

#### ONLY FOR LUBUNTU

#sudo apt-get remove -y chromium-browser firefox
#sudo apt-get remove -y abiword-common abiword libabiword-2.9 sylpheed sylpheed-plugins sylpheed-doc sylpheed-i18n gnumeric-common gnumeric xpad mtpaint evince-common evince ace-of-penguins
#sudo apt-get remove -y gxine libxine1 libxine1-x mplayer2
#sudo apt-get remove -y libgmtk0 libgmtk0-data libgmlib0

####Upgrading system
#sudo apt-get -y upgrade

####Cleaning system
#sudo apt-get -y clean
#sudo apt-get -y autoremove
