#!/bin/bash

sudo curl -sSL https://get.docker.com/ | sh

sudo docker pull odoo

sudo docker pull postgres:9.4

#docker postgres

sudo docker run --restart="always" -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo --name db postgres:9.4

#docker odoo

sudo docker run --restart="always" -p 0.0.0.0:8069:8069 --name odoo --link db:db -t odoo

#service

sudo systemctl enable docker