#!/bin/bash

sudo apt-fast -y install curl

sudo curl -sSL https://get.docker.com/ | sh

#service

sudo systemctl enable docker

#docker portainer

sudo docker run -d -p 9000:9000 --restart always --name portainer -v /var/run/docker.sock:/var/run/docker.sock -v /opt/portainer:/data portainer/portainer