#!/bin/bash
######## installpackages - Installs packages & necessary repos - script 1

#### Remove all your repos
#sudo rm -f -r /etc/apt/sources.list.d/*

#### Upgrading system
#sudo apt-get -y update
#sudo apt-get -y upgrade
##sudo apt-get -y dist-upgrade
##sudo apt-get -y install xxx --no-remove --force-yes

######## Backup & Sync

#

######## OS & Utilities

#### apt-fast
#http://www.atareao.es/ubuntu/liberado-apt-fast-1-6-6-con-configuracion-y-desde-ppa-oficial/
#http://www.atareao.es/ubuntu/instalar-desde-el-terminal-a-velocidad-de-vertigo-con-apt-fast/
##sudo add-apt-repository -y ppa:apt-fast/stable
sudo add-apt-repository -y ppa:saiarcot895/myppa
sudo apt-get -y update
sudo apt-get -y install apt-fast

#### y-ppa-manager - (launchpad getkeys + missing gpg-keys + gpg badsig errors)
sudo add-apt-repository -y ppa:webupd8team/y-ppa-manager
sudo apt-fast -y update
sudo apt-fast -y install y-ppa-manager

#### getdeb
wget -q -O- http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -
test -f /etc/apt/sources.list.d/getdeb.list || sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu vivid-getdeb apps" >> /etc/apt/sources.list.d/getdeb.list'
sudo apt-fast -y update

#### playdeb
wget -q -O- http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -
test -f /etc/apt/sources.list.d/playdeb.list || sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu vivid-getdeb games" >> /etc/apt/sources.list.d/playdeb.list'
sudo apt-fast -y update

#### mtp support
#sudo add-apt-repository -y ppa:langdalepl/gvfs-mtp
#sudo apt-fast -y update & dist-upgrade
sudo apt-fast -y install mtp-tools mtpfs

#### plank testing PPA - http://www.noobslab.com/2014/08/install-plank-dock-and-plank-themer.html
##sudo add-apt-repository -y ppa:docky-core/stable
#sudo add-apt-repository -y ppa:ricotz/docky
#sudo apt-fast -y update
#sudo apt-fast -y install plank

#### Install ati propietary driver cmd
#https://help.ubuntu.com/community/BinaryDriverHowto/AMD

#### Install nvidia propietary driver cmd
##sudo apt-fast -y install nvidia-graphics-drivers-346	#EXAMPLE

#### xorg-edgers - Possibly Unstable - Contains "bleeding-edge" graphics/system packages which may be unstable - more updated than ppa:ubuntu-x-swat/x-updates
#sudo add-apt-repository -y ppa:xorg-edgers/ppa
#sudo apt-fast -y update
#sudo apt-fast -y dist-upgrade

#how to uninstall unstable packages
#way 1 -> sudo ppa-purge -y ppa:xorg-edgers/ppa ppa:oibaf/graphics-drivers ppa:graphics-drivers/ppa
#way 2 -> sudo ppa-purge -y xorg-edgers oibaf graphics-drivers

#### oibaf - Possibly Unstable
#sudo add-apt-repository -y ppa:oibaf/graphics-drivers
#sudo apt-fast -y update
#sudo apt-fast -y dist-upgrade

#### graphics-drivers-team - Possibly Unstable
#sudo add-apt-repository -y ppa:graphics-drivers/ppa
#sudo apt-fast -y update
#sudo apt-fast -y dist-upgrade

#### keepassx daily
sudo add-apt-repository -y ppa:keepassx/daily
sudo apt-fast -y update
sudo apt-fast -y install keepassx

#### keepassx stable
#sudo apt-fast -y install keepassx

#### ubuntu-restricted-extras
sudo apt-fast -y install ubuntu-restricted-extras

#### ttf-ancient-fonts
sudo apt-fast -y install ttf-ancient-fonts

#### synaptic
sudo apt-fast -y install synaptic

#### preload
sudo apt-fast -y install preload

#### prelink
sudo apt-fast -y install prelink

#### gdebi
sudo apt-fast -y install gdebi

#### ppa-purge
sudo apt-fast -y install ppa-purge

#### gnome-disk-utility
sudo apt-fast -y install gnome-disk-utility

#### gparted
sudo apt-fast -y install gparted

#### mate-tweak
sudo apt-fast -y install mate-tweak

######## Desktop Environment

#

######## Themes

#### vibrancy-colors icon theme
sudo add-apt-repository -y ppa:ravefinity-project/ppa
sudo apt-fast -y update
sudo apt-fast install vibrancy-colors

######## Language packages
sudo apt-fast -y install aspell aspell-en aspell-es

######## Security & Privacy

#### gufw
sudo apt-fast -y install gufw

######## CD/DVD Tools

#

######## Photos & Graphics

#### gimp
#sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp-edge
sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp
sudo apt-fast -y update
sudo apt-fast -y install gimp gimp-plugin-registry

#### krita
#http://xubuntugeek.blogspot.com.es/2013/12/how-to-install-lastest-krita-in-xubuntu.html
#http://dimula73.blogspot.com.es/2013/05/krita-lime-ppa-always-fresh-versions.html
sudo add-apt-repository -y ppa:dimula73/krita		# bleeding edge build
sudo apt-fast -y update
sudo apt-fast -y install krita-2.9
sudo mv /usr/share/applications/kde4/krita.desktop /usr/share/applications/

#### gnome-exe-thumbnailer
sudo apt-fast -y install gnome-exe-thumbnailer

#### shutter
sudo apt-fast -y install shutter

######## Audio & Music

#

######## Videos & Movies

#

######## All multimedia content

#### ffmpeg
#sudo add-apt-repository -y ppa:kirillshkrogalev/ffmpeg-next
#sudo apt-fast -y update
sudo apt-fast -y install ffmpeg

#### vlc daily
sudo add-apt-repository -y ppa:videolan/master-daily
sudo apt-fast -y update
sudo apt-fast -y install vlc vlc-plugin-pulse libvlc5

#### vlc stable
#sudo add-apt-repository -y ppa:videolan/stable-daily
#sudo apt-fast -y update
#sudo apt-fast -y install vlc vlc-plugin-pulse libvlc5

######## Development

#### notepadqq
sudo add-apt-repository -y ppa:notepadqq-team/notepadqq
sudo apt-fast -y update
sudo apt-fast -y install notepadqq notepadqq-gtk

#### openjdk-8
#sudo add-apt-repository -y ppa:maarten-fonville/ppa
sudo add-apt-repository -y ppa:mamarley/updates
sudo apt-fast -y update
sudo apt-fast -y install icedtea-8-plugin openjdk-8-jre #icedtea-7-plugin openjdk-7-jre icedtea-9-plugin openjdk-9-jre

#### openjdk-7
#sudo apt-fast -y install icedtea-7-plugin openjdk-7-jre

#### openjdk-9
#sudo apt-fast -y install icedtea-9-plugin openjdk-9-jre

#### Qt dependencies
sudo apt-fast -y install mesa-common-dev libglu1-mesa-dev

######## Web Browsers

#### google-chrome-stable
#wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
#test -f /etc/apt/sources.list.d/google-chrome.list || sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
#sudo apt-fast -y update
#sudo apt-fast -y install google-chrome-stable

#### google-chrome-unstable
#wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
#test -f /etc/apt/sources.list.d/google-chrome-unstable.list || sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome-unstable.list'
#sudo apt-fast -y update
#sudo apt-fast -y install google-chrome-unstable

#### chromium stable
sudo apt-fast -y install chromium-browser chromium-browser-l10n chromium-codecs-ffmpeg-extra

#### PPA for Ubuntu Mozilla Security Team
sudo add-apt-repository -y ppa:ubuntu-mozilla-security/ppa
sudo apt-fast -y update
sudo apt-fast -y install firefox firefox-locale-es

#### pepper-flash - for chromium
##pepper-flash-player from official repos
##http://www.webupd8.org/2014/01/pepper-flash-player-installer-for.html
sudo apt-fast -y install pepperflashplugin-nonfree
##sudo update-pepperflashplugin-nonfree --install
##sudo update-pepperflashplugin-nonfree --uninstall - TO UNINSTALL

#### pepper-flash - for firefox
sudo add-apt-repository -y ppa:nilarimogard/webupd8
sudo apt-fast -y update
sudo apt-fast -y install pepperflashplugin-nonfree freshplayerplugin

######## Social

#

######## File Management

#### Compress/Uncompress utils
sudo apt-fast -y install rar unrar unace p7zip-full p7zip-rar p7zip sharutils mpack arj cabextract

######## File Sharing

#### jdownloader stable
#sudo add-apt-repository -y ppa:jd-team/jdownloader
#sudo apt-fast -y install jdownloader

#### jdownloader beta
wget http://installer.jdownloader.org/JD2SilentSetup_x64.sh
chmod +rwx JD2SilentSetup_x64.sh
su usuario -c ./JD2SilentSetup_x64.sh
rm JD2SilentSetup_x64.sh

######## News & Books

#

######## Office & Productivity

#### libreoffice
#sudo add-apt-repository -y ppa:libreoffice/libreoffice-prereleases
sudo add-apt-repository -y ppa:libreoffice/ppa
sudo apt-fast -y update
sudo apt-fast -y install libreoffice libreoffice-help-es libreoffice-l10n-es

#### qpdfview
sudo apt-fast -y install qpdfview

######## Games

#

######## Extra

#### uninstallpackages
sudo apt-fast -y remove atril tilda pidgin* thunderbird* adobe-flashplugin flashplugin-nonfree-extrasound flashplugin-installer shotwell
#sudo apt-fast -y remove firefox firefox-locale-es firefox-locale-en xul-ext-ubufox

#### Upgrading system
#sudo apt-get -y upgrade
#sudo apt-get -y dist-upgrade

#### Repairing system 2/2
#sudo apt-get -f install

#### Cleaning system
#sudo apt-get -f install
sudo apt-get -y autoremove
#sudo apt-get -y autoclean
#sudo apt-get -y clean
