#!/bin/bash
####ubuntupackages v2014.05.06 alpha
########installsources

rm -f -r /etc/apt/sources.list.d/*

#### google-chrome
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'

#### gimp
sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp/

#### y-ppa-manager - launchpad getkeys
sudo add-apt-repository -y ppa:webupd8team/y-ppa-manager/

#### variety-peterlevi
sudo add-apt-repository -y ppa:peterlevi/ppa

#### VLC
sudo add-apt-repository -y ppa:ed10vi86/video

#### 0ad
sudo add-apt-repository -y ppa:wfg/0ad

#### Getdeb
wget -q -O- http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -
sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu trusty-getdeb apps" >> /etc/apt/sources.list.d/getdeb_apps.list'
sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu trusty-getdeb games" >> /etc/apt/sources.list.d/getdeb_games.list'

#### LibreOffice
sudo add-apt-repository -y ppa:libreoffice/ppa

#### photo
sudo add-apt-repository -y ppa:samrog131/ppa

#### winusb
sudo add-apt-repository -y ppa:colingille/freshlight

#### systemback - HIGHLY RECOMMENDED!
sudo apt-add-repository -y ppa:nemh/systemback

#### WebUpd8: Audacious, unity-reboot, etc
sudo add-apt-repository -y ppa:nilarimogard/webupd8

#### New apt
#sudo add-apt-repository -y ppa:mvo/apt-src-ftparchive

#### firefox aurora
#sudo add-apt-repository -y ppa:ubuntu-mozilla-daily/firefox-aurora

#### GNOME3 Extra Apps: Nautilus, etc
#sudo add-apt-repository -y ppa:gnome3-team/gnome3

#### Xorg Edgers - Unstable - Contains "bleeding-edge" graphics/system packages which may be unstable
# sudo add-apt-repository -y ppa:xorg-edgers/ppa
# how to uninstall it -> sudo ppa-purge xorg-edgers  -> sudo ppa-purge ubuntu-x-swat

########################################################### EXTRA

#### cairo-dock
#sudo add-apt-repository -y ppa:cairo-dock-team/weekly

#### TimeShift
#sudo add-apt-repository -y ppa:teejee2008/ppa

#### Ubuntu phone sdk
#sudo add-apt-repository -y ppa:canonical-qt5-edgers/qt5-proper
#sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa

#### Chromium dev & beta channel
#sudo add-apt-repository -y ppa:saiarcot895/chromium-dev  
#sudo add-apt-repository -y ppa:saiarcot895/chromium-beta 

#### X Updates - only recommended for latest graphic cards drivers
#sudo add-apt-repository -y ppa:ubuntu-x-swat/x-updates/

#### i-nex
#sudo add-apt-repository -y ppa:nemh/gambas3
#sudo add-apt-repository -y ppa:i-nex-development-team/stable

#### pidgin
#sudo add-apt-repository -y ppa:pidgin-developers/ppa

#### Java
#sudo add-apt-repository -y ppa:webupd8team/java

#### Midori
#sudo add-apt-repository -y ppa:midori/midori-dev
#sudo add-apt-repository -y ppa:midori/ppa

#### Wine
#sudo add-apt-repository -y ppa:ubuntu-wine/ppa

#### Steam Login
#sudo add-apt-repository -y ppa:thor27-gmail/steam-desktop

#### backintime testing
#sudo add-apt-repository -y ppa:bit-team/stable

#### grub-customizer
#sudo add-apt-repository -y ppa:danielrichter2007/grub-customizer/

#### tor-browser
#sudo add-apt-repository -y ppa:webupd8team/tor-browser

#### ualinux - PRECISE
#wget -q -O- http://archive.ualinux.com/ualinux.key | sudo apt-key add -
#sudo sh -c 'echo "deb http://archive.ualinux.com/ubuntu precise main" >> /etc/apt/sources.list.d/ualinux.list'

#### UNetbootin - May be in official repo
#sudo add-apt-repository -y ppa:gezakovacs/ppa

#### Ubuplus - PRECISE
#sudo add-apt-repository -y ppa:luismtc20/ppa

#### Hotot - May be in official repo
#sudo add-apt-repository -y ppa:jimmyxu/hotot

#### E17
#sudo add-apt-repository -y ppa:hannes-janetzek/enlightenment-svn

#### muCommander (unstable)
#sudo wget -O - http://apt.mucommander.com/apt.key | sudo apt-key add -
#sudo sh -c 'echo "deb http://apt.mucommander.com unstable main non-free contrib " >> /etc/apt/sources.list.d/mucommander.list'

#### multisystem
#wget -q http://liveusb.info/multisystem/depot/multisystem.asc -O- | sudo apt-key add -
#sudo sh -c 'echo "deb http://liveusb.info/multisystem/depot all main" >> /etc/apt/sources.list.d/multisystem.list'

#### emerald
#sudo add-apt-repository -y ppa:brainpower/testing/

#### jupiter
#sudo add-apt-repository -y ppa:webupd8team/jupiter

#### Audacity
#sudo add-apt-repository -y ppa:audacity-team/daily

#### SpaceFM - problems
#sudo add-apt-repository -y ppa:mati75/lubuntu

#### jdownloader - Recommended v2 BETA http://installer.jdownloader.org/JD2SilentSetup_x64.sh
#sudo add-apt-repository -y ppa:jd-team/jdownloader/

#### spotify
#sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 94558F59
#sudo sh -c 'echo "deb http://repository.spotify.com stable non-free" >> /etc/apt/sources.list.d/spotify.list'

#### MATE Desktop Environment
#sudo apt-get --yes --force-yes install mate-archive-keyring
#sudo sh -c 'echo "deb http://packages.mate-desktop.org/repo/ubuntu raring main" >> /etc/apt/sources.list.d/MATE.list'

#### CPU Frequency Scaling
#sudo add-apt-repository -y ppa:artfwo/ppa

#### Psensor
#sudo add-apt-repository -y ppa:alexmurray/indicator-sensors

#### remastersys - PRECISE but works on RARING - systemback is preferible
#wget -O - http://www.remastersys.com/ubuntu/remastersys.gpg.key | sudo apt-key add -
#sudo sh -c 'echo "deb http://www.remastersys.com/ubuntu precise main" >> /etc/apt/sources.list.d/remastersys.list'

########################################################### ONLY FOR UBUNTU WITH UNITY SURELY

#### unity-tweak-tool
sudo add-apt-repository -y ppa:freyja-dev/unity-tweak-tool-daily

#### Ubuntu Tweak
sudo add-apt-repository -y ppa:tualatrix/ppa
#sudo add-apt-repository -y ppa:freyja-dev/tualatrix

#### classicmenu-indicator & Unsettings
sudo add-apt-repository -y ppa:diesch/testing

#### appgrid
#sudo add-apt-repository -y ppa:appgrid/stable

#### my-weather-indicator
#sudo add-apt-repository -y ppa:atareao/atareao

########################################################### ONLY FOR...

#### WebUpd8 Unstable: Synaptic - only for 13.10 or less
#sudo add-apt-repository -y ppa:webupd8team/unstable

#### Gthumb - only for 13.04 or less
#sudo add-apt-repository -y ppa:webupd8team/gthumb

#### Kazam - In official stable repo - only for 13.04 or less
#sudo add-apt-repository -y ppa:kazam-team/unstable-series

#### Intel Linux Graphics Installer - only for 13.10 or less
#wget --no-check-certificate https://download.01.org/gfx/RPM-GPG-KEY-ilg -O - | sudo apt-key add -
#wget --no-check-certificate https://download.01.org/gfx/RPM-GPG-KEY-ilg-2 -O - | sudo apt-key add -
#sudo sh -c 'echo echo "deb https://download.01.org/gfx/ubuntu/13.10/main saucy main" >> /etc/apt/sources.list.d/intellinuxgraphics.list'

########################################################### NOT NECESSARY

#### VirtualBox - also in official sources
#wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
#sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -sc)  contrib" >> /etc/apt/sources.list.d/virtualbox.list'

#### PlayOnLinux - also in official sources - PRECISE - Download from http://www.playonlinux.com/script_files/PlayOnLinux/4.2.1/PlayOnLinux_4.2.1.deb
#wget -q "http://deb.playonlinux.com/public.gpg" -O- | sudo apt-key add -
#sudo wget http://deb.playonlinux.com/playonlinux_precise.list -O /etc/apt/sources.list.d/playonlinux.list

#### pepper-flash - only for chromium I think, but now is on official sources
#sudo add-apt-repository -y ppa:skunk/pepper-flash

#### Medibuntu - DISCONTINUED
#sudo -E wget --output-document=/etc/apt/sources.list.d/medibuntu.list http://www.medibuntu.org/sources.list.d/$(lsb_release -cs).list
#sudo apt-get update
#sudo apt-get --yes --quiet --allow-unauthenticated install medibuntu-keyring