#!/bin/bash
####ubuntupackages v2013.12.07 alpha
########################################################installsources

rm -f -r /etc/apt/sources.list.d/*

#### Chromium dev
sudo add-apt-repository -y ppa:saiarcot895/chromium-dev

#### Wine
sudo add-apt-repository -y ppa:ubuntu-wine/ppa

#### gimp
sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp/

#### y-ppa-manager - launchpad getkeys
sudo add-apt-repository -y ppa:webupd8team/y-ppa-manager/

#### variety-peterlevi
sudo add-apt-repository -y ppa:peterlevi/ppa

#### VLC
sudo add-apt-repository -y ppa:videolan/stable-daily

#### Java
sudo add-apt-repository -y ppa:webupd8team/java

#### Getdeb
wget -q -O- http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -
sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu raring-getdeb apps" >> /etc/apt/sources.list.d/getdeb_apps.list'
sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu raring-getdeb games" >> /etc/apt/sources.list.d/getdeb_games.list'

#### Midori
sudo add-apt-repository -y ppa:midori/midori-dev
#sudo add-apt-repository -y ppa:midori/ppa

#### EXTRA

#### LibreOffice
sudo add-apt-repository -y ppa:libreoffice/ppa

#### grub-customizer
sudo add-apt-repository -y ppa:danielrichter2007/grub-customizer/

#### backintime testing
sudo add-apt-repository -y ppa:bit-team/stable

#### firefox aurora
sudo add-apt-repository -y ppa:ubuntu-mozilla-daily/firefox-aurora

#### Medibuntu
#sudo -E wget --output-document=/etc/apt/sources.list.d/medibuntu.list http://www.medibuntu.org/sources.list.d/$(lsb_release -cs).list
#sudo apt-get update
#sudo apt-get --yes --quiet --allow-unauthenticated install medibuntu-keyring

#### VirtualBox
#wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
#sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian raring contrib" >> /etc/apt/sources.list.d/virtualbox.list'

#### PlayOnLinux - PRECISE - Download from http://www.playonlinux.com/script_files/PlayOnLinux/4.2.1/PlayOnLinux_4.2.1.deb
#### wget -q "http://deb.playonlinux.com/public.gpg" -O- | sudo apt-key add -
#### sudo wget http://deb.playonlinux.com/playonlinux_precise.list -O /etc/apt/sources.list.d/playonlinux.list

#### remastersys - PRECISE but works on RARING
#wget -O - http://www.remastersys.com/ubuntu/remastersys.gpg.key | sudo apt-key add -
#sudo sh -c 'echo "deb http://www.remastersys.com/ubuntu precise main" >> /etc/apt/sources.list.d/remastersys.list'

#### WebUpd8 Unstable: Synaptic
#sudo add-apt-repository -y ppa:webupd8team/unstable

#### GNOME3 Extra Apps: Nautilus, etc
#sudo add-apt-repository -y ppa:gnome3-team/gnome3

#### ualinux - PRECISE
#### wget -q -O- http://archive.ualinux.com/ualinux.key | sudo apt-key add -
#### sudo sh -c 'echo "deb http://archive.ualinux.com/ubuntu precise main" >> /etc/apt/sources.list.d/ualinux.list'

#### Kazam - May be in official repo
#### sudo add-apt-repository -y ppa:kazam-team/unstable-series

#### UNetbootin - May be in official repo
#### sudo add-apt-repository -y ppa:gezakovacs/ppa

#### Ubuplus - PRECISE
#### sudo add-apt-repository -y ppa:luismtc20/ppa

#### Hotot - May be in official repo
#### sudo add-apt-repository -y ppa:jimmyxu/hotot

#### X Updates - PRECISE
#### sudo add-apt-repository -y ppa:ubuntu-x-swat/x-updates/

#### Xorg Edgers - Unstable
#### sudo add-apt-repository -y ppa:xorg-edgers/ppa
#### cómo desinstalar -> sudo ppa-purge xorg-edgers  -> sudo ppa-purge ubuntu-x-swat

#### E17
#sudo add-apt-repository -y ppa:hannes-janetzek/enlightenment-svn

#### Unsettings
#sudo add-apt-repository -y ppa:diesch/testing

#### WebUpd8: Audacious, unity-reboot, etc
#sudo add-apt-repository -y ppa:nilarimogard/webupd8

#### muCommander (unstable)
#sudo wget -O - http://apt.mucommander.com/apt.key | sudo apt-key add -
#sudo sh -c 'echo "deb http://apt.mucommander.com unstable main non-free contrib " >> /etc/apt/sources.list.d/mucommander.list'

#### multisystem
#wget -q http://liveusb.info/multisystem/depot/multisystem.asc -O- | sudo apt-key add -
#sudo sh -c 'echo "deb http://liveusb.info/multisystem/depot all main" >> /etc/apt/sources.list.d/multisystem.list'

#### emerald
#sudo add-apt-repository -y ppa:brainpower/testing/

#### jupiter
#sudo add-apt-repository -y ppa:webupd8team/jupiter

#### cairo-dock
#sudo add-apt-repository -y ppa:cairo-dock-team/weekly

#### Audacity
#sudo add-apt-repository -y ppa:audacity-team/daily

#### SpaceFM - problems
#sudo add-apt-repository -y ppa:mati75/lubuntu

#### Ubuntu Tweak
#sudo add-apt-repository -y ppa:tualatrix/ppa

#### jdownloader - Recommended v2 BETA http://installer.jdownloader.org/JD2SilentSetup_x64.sh
#sudo add-apt-repository -y ppa:jd-team/jdownloader/

#### spotify
#sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 94558F59
#sudo sh -c 'echo "deb http://repository.spotify.com stable non-free" >> /etc/apt/sources.list.d/spotify.list'

#### photo
#sudo add-apt-repository -y ppa:samrog131/ppa

#### Gthumb
#sudo add-apt-repository -y ppa:webupd8team/gthumb

#### MATE Desktop Environment
#sudo apt-get --yes --force-yes install mate-archive-keyring
#sudo sh -c 'echo "deb http://packages.mate-desktop.org/repo/ubuntu raring main" >> /etc/apt/sources.list.d/MATE.list'

#### CPU Frequency Scaling
#sudo add-apt-repository -y ppa:artfwo/ppa

#### Psensor
#sudo add-apt-repository -y ppa:alexmurray/indicator-sensors