#!/bin/bash
######## installpackages - Installs packages & necessary repos - script 3

######## Backup & Sync

#### DirSyncPro
sudo mkdir /opt/DirSyncPro
sudo wget http://kent.dl.sourceforge.net/project/directorysync/DirSync%20Pro%20%28stable%29/1.50/DirSyncPro-1.50-Linux.zip -O /opt/DirSyncPro/DirSyncPro-1.50-Linux.zip
sudo wget http://dirsyncpro.org/images/dirsyncpro.png -O /opt/DirSyncPro/dirsyncpro.png
sudo unzip /opt/DirSyncPro/DirSyncPro-1.50-Linux.zip -d /opt/DirSyncPro
sudo rm /opt/DirSyncPro/DirSyncPro-1.50-Linux.zip
sudo chmod +rwx /opt/DirSyncPro/DirSyncPro-1.50-Linux/dirsyncpro.jar

test -f /usr/share/applications/dirsyncpro.desktop || sudo sh -c 'echo "[Desktop Entry]
Type=Application
Name=DirSyncPro
Comment=Sync your files!
Categories=System
Exec=/opt/DirSyncPro/DirSyncPro-1.50-Linux/dirsyncpro.jar
Icon=/opt/DirSyncPro/dirsyncpro.png" >> /usr/share/applications/dirsyncpro.desktop'
##sudo ln -s /opt/DirSyncPro/DirSyncPro-1.50-Linux/dirsyncpro.jar ~/Escritorio/DirSyncPro

#### systemback - HIGHLY RECOMMENDED!
sudo apt-add-repository -y ppa:nemh/systemback
sudo apt-fast -y update
sudo apt-fast -y install systemback

######## OS & Utilities

#### albert
sudo apt-add-repository -y ppa:nilarimogard/webupd8
sudo apt-fast -y update
sudo apt-fast -y install albert

#### mutate
sudo apt-add-repository -y ppa:mutate/ppa
sudo apt-fast -y update
sudo apt-fast -y install mutate

#### undistract-me - http://lamiradadelreplicante.com/2015/01/15/undistract-me-nos-avisa-cuando-un-comando-ha-terminado-de-ejecutarse-en-la-terminal/
sudo apt-fast -y install undistract-me

#### appgrid
sudo add-apt-repository -y ppa:appgrid/stable
sudo apt-fast -y update
sudo apt-fast -y install appgrid

#### postinstallerf
## ancient version
#wget -c http://sourceforge.net/projects/postinstaller/files/ubuntu/app-install-data-postinstallerf_1.0-6_all.deb
#wget -c http://sourceforge.net/projects/postinstaller/files/ubuntu/postinstallerf_1.5-13_all.deb
#sudo add-apt-repository -y ppa:webupd8team/y-ppa-manager
#sudo apt-fast -y update
#sudo apt-fast -y install yad packagekit
#sudo dpkg -i app-install-data-postinstallerf_1.0-6_all.deb
#sudo dpkg -i postinstallerf_1.5-13_all.deb
## latest version
wget -c http://sourceforge.net/projects/postinstaller/files/ubuntu/app-install-data-postinstallerf_1.0-6_all.deb
wget -c http://sourceforge.net/projects/postinstaller/files/fedora/releases/21/x86_64/postinstallerf-1.5-21.fc21.noarch.rpm
sudo add-apt-repository -y ppa:webupd8team/y-ppa-manager
sudo apt-fast -y update
sudo apt-fast -y install yad packagekit
sudo dpkg -i app-install-data-postinstallerf_1.0-6_all.deb
sudo apt-fast -y install alien dpkg-dev debhelper build-essential
sudo alien postinstallerf-1.5-21.fc21.noarch.rpm
sudo dpkg -i postinstallerf_1.5-22_all.deb

#### variety-peterlevi
#sudo add-apt-repository -y ppa:peterlevi/ppa
#sudo add-apt-repository -y ppa:variety/next
sudo add-apt-repository -y ppa:variety/daily
sudo apt-fast -y update
sudo apt-fast -y install variety

#### HP
sudo apt-fast -y install hplip hplip-gui

#### Various
sudo apt-fast -y install uck	#ubuntu customization kit

######## Desktop Environment

#

######## Themes

#

######## Language packages

#

######## Security & Privacy

#

######## CD/DVD Tools

#

######## Photos & Graphics

#### krita
#http://xubuntugeek.blogspot.com.es/2013/12/how-to-install-lastest-krita-in-xubuntu.html
#http://dimula73.blogspot.com.es/2013/05/krita-lime-ppa-always-fresh-versions.html
sudo add-apt-repository -y ppa:dimula73/krita		# bleeding edge build
sudo apt-fast -y update
sudo apt-fast -y install krita-testing krita-testing-dbg krita-testing-l10n-es
#sudo restart lightdm
#to execute run "krita"
#sudo add-apt-repository ppa:kubuntu-ppa/backports
#sudo apt-fast update
#sudo apt-fast install krita kritasketch

######## Audio & Music

#

######## Videos & Movies

#

######## All multimedia content

#

######## Development

#### ubuntu-emulator
#http://www.webupd8.org/2014/03/ubuntu-touch-emulator-installation-and.html
#http://www.webupd8.org/2013/11/experimental-ubuntu-touch-emulator.html
sudo apt-fast -y install ubuntu-emulator

#### Kicad
sudo add-apt-repository -y ppa:js-reynaud/ppa-kicad
sudo add-apt-repository -y ppa:adamwolf/kicad-testing-daily		#abandoned
sudo apt-fast -y update
sudo apt-fast -y install kicad

##### Fritzing
wget -q -O- http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -
test -f /etc/apt/sources.list.d/getdeb_apps.list || sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu utopic-getdeb apps" >> /etc/apt/sources.list.d/getdeb_apps.list'
test -f /etc/apt/sources.list.d/getdeb_games.list || sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu utopic-getdeb games" >> /etc/apt/sources.list.d/getdeb_games.list'
sudo apt-fast -y update
sudo apt-fast -y install fritzing

######## Web Browsers

#


######## Social

#

######## File Management

#

######## File Sharing

#

######## News & Books

#

######## Office & Productivity

#

######## Games

#### Various
sudo apt-fast -y install scourge violetland bofh csmash cdogs-sdl djl
