#!/bin/bash
######## installpackages - Installs packages & necessary repos - script 4

######## Backup & Sync

#### Holo Backup
sudo mkdir "/opt/Holo Backup"
wget https://codeload.github.com/omegavesko/SimpleADBBackup/legacy.tar.gz/master -O "/opt/Holo Backup/omegavesko-SimpleADBBackup-0aac4aa%20.tar.gz"
tar xvfz "/opt/Holo Backup/omegavesko-SimpleADBBackup-0aac4aa%20.tar.gz"
sudo chmod +rwx "/opt/Holo Backup/omegavesko-SimpleADBBackup-0aac4aa/HoloBackupLinux"
sudo sh -c 'echo "[Desktop Entry]
Type=Application
Name=Holo Backup
Comment=Backup your droid!
Categories=System
Exec="/opt/Holo Backup/omegavesko-SimpleADBBackup-0aac4aa/HoloBackupLinux"
Icon='
##sudo ln -s "/opt/Holo Backup/omegavesko-SimpleADBBackup-0aac4aa/HoloBackupLinux" "~/Escritorio/Holo Backup"

#### backintime testing
sudo add-apt-repository -y ppa:bit-team/stable
sudo apt-fast -y update
sudo apt-fast -y install backintime-gnome

#### TimeShift
#http://www.howtogeek.com/206491/how-to-restore-your-ubuntu-linux-system-to-its-previous-state/
sudo add-apt-repository -y ppa:teejee2008/ppa
sudo apt-fast -y update
sudo apt-fast -y install timeshift

#### Insync
wget -qO - https://d2t3ff60b2tol4.cloudfront.net/services@insynchq.com.gpg.key | sudo apt-key add -
test -f /etc/apt/sources.list.d/insync.list || sudo sh -c 'echo "deb http://apt.insynchq.com/ubuntu trusty non-free contrib" >> /etc/apt/sources.list.d/insync.list'
sudo apt-fast -y update
sudo apt-fast -y install insync insync-caja
##referal
#https://www.insynchq.com/r/106908789160316075573

#### Spideroak
#http://www.rubynginx.com/index.php/2012/10/11/install-spideroak-on-ubuntu-12-04/																												
#https://spideroak.com/faq/questions/65/what_are_the_apt_sources_lines_for_spideroak/																												
wget -qO - https://spideroak.com/dist/spideroak-apt-2013.asc | sudo apt-key add -
test -f /etc/apt/sources.list.d/spideroak.list || sudo sh -c 'echo "deb http://apt.spideroak.com/ubuntu-spideroak-hardy/ release restricted" >> /etc/apt/sources.list.d/spideroak.list'
sudo apt-fast -y update
sudo apt-fast -y install spideroak

#### Various
sudo apt-fast -y install sbackup-plugins-fuse grsync unison-gtk freefilesync	#http://planetubuntu.es/post/como-sincronizar-2-equipos-de-manera-bidireccional-con-unison

########OS & Utilities

#### cairo-dock - TO TEST
#Run cairo-dock at startup in compatibility transparency mode with a few window managers - http://glx-dock.org/ww_page.php?p=Recurrents%20problems&lang=en
#sudo add-apt-repository -y ppa:cairo-dock-team/ppa
sudo add-apt-repository -y ppa:cairo-dock-team/weekly
sudo apt-fast -y update
sudo apt-fast -y install cairo-dock
mkdir ~/.config/autostart
rm ~/.config/autostart/cairo-dock.desktop
test -f ~/.config/autostart/cairo-dock.desktop || sh -c 'echo "[Desktop Entry]
Type=Application
Exec=cairo-dock -W
Hidden=false
X-MATE-Autostart-enabled=true
Name[es_ES]=Cairo Dock
Name=Cairo Dock
Comment[es_ES]=
Comment=" >> ~/.config/autostart/cairo-dock.desktop'

# Disable bug error notifications
sudo sed -i s/enabled=1/enabled=0/g /etc/default/apport

#### unattended-upgrades - NOT WORKING
#http://almamu.com/wordpress/configurar-las-actualizaciones-automaticas-en-ubuntu-server/
#http://241931348f64b1d1.wordpress.com/2013/01/24/how-to-configure-automatic-update-on-ubuntu-server/
#http://www.redeszone.net/2014/12/12/habilita-las-actualizaciones-de-seguridad-automaticas-en-ubuntu/
#http://www.taringa.net/posts/linux/13681417/Instalar-automaticamente-actualizaciones-en-Ubuntu.html
#http://askubuntu.com/questions/172524/how-can-i-check-if-automatic-updates-are-enabled#172527
sudo apt-fast -y install unattended-upgrades
sudo dpkg-reconfigure -plow unattended-upgrades

## /etc/apt/apt.conf.d/10periodic

#Replace this:

#APT::Periodic::Update-Package-Lists "1";
#APT::Periodic::Download-Upgradeable-Packages "0";
#APT::Periodic::AutocleanInterval "0";

#With this:

#APT::Periodic::Enable "1";
#APT::Periodic::Update-Package-Lists "1";
#APT::Periodic::Download-Upgradeable-Packages "1";
#APT::Periodic::AutocleanInterval "5";
#APT::Periodic::Unattended-Upgrade "1";
#APT::Periodic::RandomSleep "1800";

## /etc/apt/apt.conf.d/50unattended-upgrades
#uncomment - "${distro_id}:${distro_codename}-updates";

#### grub-customizer
sudo add-apt-repository -y ppa:danielrichter2007/grub-customizer/
sudo apt-fast -y update
sudo apt-fast -y install grub-customizer

#### VirtualBox (1)
wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
test -f /etc/apt/sources.list.d/virtualbox.list || sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -sc)  contrib" >> /etc/apt/sources.list.d/virtualbox.list'
sudo apt-fast -y update
sudo apt-fast -y install virtualbox-4.3 dkms

#### VirtualBox (2)
#wget -q -O - http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc | sudo apt-key add -
#test -f /etc/apt/sources.list.d/virtualbox.org.list || sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian utopic non-free contrib" >> /etc/apt/sources.list.d/virtualbox.org.list'
#sudo apt-fast -y update
#sudo apt-fast -y upgrade
#sudo apt-fast -y install virtualbox-4.3 virtualbox-guest-additions-iso virtualbox-guest-utils virtualbox-guest-x11 virtualbox-qt

#### PlayOnLinux
wget http://www.playonlinux.com/script_files/PlayOnLinux/4.2.5/PlayOnLinux_4.2.5.deb
sudo dpkg -i PlayOnLinux*.deb
rm PlayOnLinux*.deb

#### Intel Linux Graphics Installer
#wget --no-check-certificate https://download.01.org/gfx/RPM-GPG-KEY-ilg -O - | sudo apt-key add -
#wget --no-check-certificate https://download.01.org/gfx/RPM-GPG-KEY-ilg-2 -O - | sudo apt-key add -
#test -f /etc/apt/sources.list.d/intellinuxgraphics.list || sudo sh -c 'echo echo "deb https://download.01.org/gfx/ubuntu/14.04/main/ trusty main" >> /etc/apt/sources.list.d/intellinuxgraphics.list'

#### muCommander (unstable)
sudo wget -O - http://apt.mucommander.com/apt.key | sudo apt-key add -
test -f /etc/apt/sources.list.d/mucommander.list || sudo sh -c 'echo "deb http://apt.mucommander.com unstable main non-free contrib " >> /etc/apt/sources.list.d/mucommander.list'
sudo apt-fast -y update
sudo apt-fast -y install mucommander

#### GNOME3 Extra Apps: Nautilus, etc
sudo add-apt-repository -y ppa:gnome3-team/gnome3
sudo apt-fast -y update

#### New apt
sudo add-apt-repository -y ppa:mvo/apt-src-ftparchive
sudo apt-fast -y update

#### Unstable Synaptic 
sudo add-apt-repository -y ppa:webupd8team/unstable
sudo apt-fast -y update
sudo apt-fast -y install synaptic

#### X Updates - only recommended for latest graphic cards drivers - less updated than ppa:xorg-edgers/ppa
sudo add-apt-repository -y ppa:ubuntu-x-swat/x-updates/
sudo apt-fast -y update
sudo apt-fast -y dist-upgrade

#### Teamviewer - POSSIBLY ERROR
#http://www.teamviewer.com/es/download/linux.aspx
wget http://download.teamviewer.com/download/teamviewer_i386.deb
sudo dpkg -i teamviewer_i386.deb
rm teamviewer_i386.deb

#### i-nex
sudo add-apt-repository -y ppa:nemh/gambas3
sudo add-apt-repository -y ppa:i-nex-development-team/stable
sudo apt-fast -y update
sudo apt-fast -y install i-nex

#### winusb
sudo add-apt-repository -y ppa:colingille/freshlight
sudo apt-fast -y update
sudo apt-fast -y install winusb

#### Ubuplus - PRECISE
#sudo add-apt-repository -y ppa:luismtc20/ppa
#sudo apt-fast -y update
#sudo apt-fast -y install ubuplus

#### jupiter	#POSSIBLY DEPRECATED
#sudo add-apt-repository -y ppa:webupd8team/jupiter
#sudo apt-fast -y update
#sudo apt-fast -y install jupiter

#### Psensor
sudo add-apt-repository -y ppa:alexmurray/indicator-sensors
sudo apt-fast -y update
sudo apt-fast -y install psensor 

#### voice-commands
#http://www.noobslab.com/2014/06/control-your-ubuntulinux-mint-system.html
sudo add-apt-repository -y ppa:baitsart/voice-commands
sudo apt-fast -y update
sudo apt-fast -y install voice-commands

#### Various
sudo apt-fast -y install inxi	# http://lamiradadelreplicante.com/2014/10/27/toda-la-informacion-de-tu-sistema-linux-con-inxi/
sudo apt-fast -y install laptop-mode-tools	#gksu lmt-config-gui - This to launch it
sudo apt-fast -y install libfile-mimeinfo-perl catfish bleachbit
sudo apt-fast -y install qtnx usb-imagewriter gddrescue testdisk baobab gsmartcontrol calendar-indicator
sudo apt-fast -y install gnome-system-tools gnome-tweak-tool
#sudo apt-fast -y install checkbox-qt - SYSTEM TESTING APP
sudo apt-fast -y install indicator-netspeed launchy
sudo apt-fast -y install xscreensaver-gl xscreensaver-gl-extra
sudo apt-fast -y install alarm-clock gmrun lm-sensors tmux xbindkeys xbindkeys-config htop pcmanfm

########Desktop Environment

#### gnome-session-fallback
sudo apt-fast -y install gnome-session-fallback

#### lxqt
#http://entornosgnulinux.com/2014/05/16/i-lxqt-0-7-0-en-ubuntu-14-04-lts-trusty-configuracion-qt/
sudo add-apt-repository -y ppa:lubuntu-dev/lubuntu-daily
sudo apt-fast -y update
sudo apt-fast -y install lxqt-metapackage lxqt-panel gtk2-engines-qtcurve pcmanfm kdelibs5-plugins lxappearance lxappearance-obconf openbox

#### budgie-desktop
#sudo add-apt-repository -y ppa:sukso96100/budgie-desktop
sudo add-apt-repository -y ppa:evolve-os/ppa	#POSSIBLY LATEST
sudo apt-fast -y update
sudo apt-fast -y install budgie-desktop

#### razorqt
sudo add-apt-repository -y ppa:razor-qt/ppa
sudo apt-fast -y update
sudo apt-fast -y install razorqt razorqt-config

#### cinnamon
#sudo add-apt-repository -y ppa:lestcape/cinnamon	#### stable for 14.04
#sudo add-apt-repository -y ppa:tsvetko.tsvetkov/cinnamon	#### stable for 14.04 & 12.04
sudo add-apt-repository -y ppa:gwendal-lebihan-dev/cinnamon-nightly		#### nightly for 14.10 & 14.04
sudo apt-fast -y update
sudo apt-fast -y install cinnamon

#### MATE Desktop Environment (1)
sudo apt-fast --yes --force-yes install mate-archive-keyring
test -f /etc/apt/sources.list.d/MATE.list || sudo sh -c 'echo "deb http://packages.mate-desktop.org/repo/ubuntu raring main" >> /etc/apt/sources.list.d/MATE.list'
sudo apt-fast -y update
sudo apt-fast -y install mate-desktop-environment

#### MATE Desktop Environment (2) - http://wiki.mate-desktop.org/download - http://wiki.mate-desktop.org/replace_unity_by_mate
#echo "deb http://repo.mate-desktop.org/archive/1.8/ubuntu $(lsb_release -cs) #main" | sudo tee /etc/apt/sources.list.d/mate-desktop.list
#wget -qO - http://mirror1.mate-desktop.org/debian/mate-archive-keyring.gpg | sudo apt-key add -
#sudo add-apt-repository -y ppa:ravefinity-project/ppa
#sudo apt-fast -y update
#sudo apt-fast install --no-install-recommends mate-desktop-environment mate-desktop-environment-extra caja-gksu caja-sendto mate-indicator-applet mate-icon-theme-faenza
#sudo apt-fast install mate-notification-daemon mate-media-pulse mate-system-tools mate-system-tools-common mate-system-monitor-common
#sudo apt-fast install ambiance-colors radiance-colors
#sudo apt-fast remove gcalctool gnome-screenshot gedit file-roller eog gnome-system-monitor gnome-system-log baobab gnome-terminal gnome-applets gnome-media gnome-power-manager gnome-screensaver
#sudo apt-fast remove gnome-calculator evince

#### enlightenment
##e20
sudo add-apt-repository -y ppa:enlightenment-git/ppa
sudo apt-fast -y update
sudo apt-fast -y install e20 terminology
##e19
#sudo add-apt-repository -y ppa:martinx/enlightenment
#sudo apt-fast -y update
#sudo apt-fast -y install enlightenment terminology

########Themes

#### ambiance and radiance themes
sudo add-apt-repository -y ppa:ravefinity-project/ppa
sudo apt-fast -y update
sudo apt-fast -y install ambiance-colors radiance-colors ubuntu-mono
sudo apt-fast -y install ambiance-blackout-flat-colors

#### ambiance-grey
sudo add-apt-repository -y ppa:noobslab/themes
sudo apt-fast -y update
sudo apt-fast -y install ambiance-grey

#### vibrancy-colors icon theme
sudo add-apt-repository -y ppa:ravefinity-project/ppa
sudo apt-fast -y update
sudo apt-fast install vibrancy-colors

######## Language packages
sudo apt-fast -y install myspell-es wspanish language-pack-es language-pack-es-base 
sudo apt-fast -y install myspell-en-gb myspell-en-us
sudo apt-fast -y install aspell aspell-en aspell-es

######## Security & Privacy
sudo apt-fast -y install seahorse

#### tor-browser
sudo add-apt-repository -y ppa:webupd8team/tor-browser
sudo apt-fast -y update
sudo apt-fast -y install tor-browser

######## CD/DVD Tools

#### Various
sudo apt-fast -y install furiusisomount devede isomaster k3b acetoneiso 

######## Photos & Graphics

#### Gthumb - only for 13.04 or less
sudo add-apt-repository -y ppa:webupd8team/gthumb
sudo apt-fast -y update
sudo apt-fast -y install gthumb

#### photo
sudo add-apt-repository -y ppa:samrog131/ppa
sudo apt-fast -y update
sudo apt-fast -y install photo 

#### Various
sudo apt-fast -y install shotwell
sudo apt-fast -y install xnviewmp xsane
sudo apt-fast -y install inkscape karbon scribus gwenview		#scribus-ng - DEV VERSION

######## Audio & Music

#### spotify - ONLY FOR 64 BITS - TO USE 32 GO TO http://repository.spotify.com/pool/non-free/s/spotify/
#sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 94558F59 - TO TEST
#sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4E9CFF4E - TO TEST
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 94558F59
test -f /etc/apt/sources.list.d/spotify.list || sudo sh -c 'echo "deb http://repository.spotify.com stable non-free" >> /etc/apt/sources.list.d/spotify.list'
sudo apt-fast -y update
sudo apt-fast -y install spotify-client

#### blockify
#http://kuboosoft.blogspot.com.es/2015/01/quita-los-molestos-anuncios-de-spotify.html
sudo apt-fast -y install python-pip python-wnck
sudo pip install http://github.com/mikar/blockify/archive/v1.7.2.zip
echo -e '[Desktop Entry]\nName=Blockify\nComment=Blocks Spotify commercials\nExec=blockify-ui\nIcon='$(python -c 'import pkg_resources; print pkg_resources.resource_filename("blockify", "data/icon-red-512.png")')'\nType=Application\nCategories=AudioVideo' | sudo tee /usr/share/applications/blockify.desktop

#### Audacity
sudo add-apt-repository -y ppa:audacity-team/daily
sudo apt-fast -y update
sudo apt-fast -y install audacity

#### PyKaraoke
#wget http://heanet.dl.sourceforge.net/project/pykaraoke/pykaraoke/0.7.5/pykaraoke-0.7.5.zip
#unzip pykaraoke-0.7.5.zip
#sudo apt-fast -y install python-dev python-pygame libwxgtk-python libsdl-dev python-mutagen
#cd pykaraoke-0.7.5
#python setup.py install
#pykaraoke

#### Various
sudo apt-fast -y install sound-juicer mixxx qtractor performous

######## Videos & Movies

#### ffmpeg
sudo add-apt-repository -y ppa:kirillshkrogalev/ffmpeg-next
sudo apt-fast -y update
sudo apt-fast -y install ffmpeg

#### Kazam - In official stable repo
#sudo add-apt-repository -y ppa:kazam-team/stable-series
#sudo add-apt-repository -y ppa:kazam-team/unstable-series
#sudo apt-fast -y update
#sudo apt-fast -y install kazam

#### VLC #### only compatible with 14.04
#sudo add-apt-repository -y ppa:ed10vi86/video
#sudo apt-fast -y update
#sudo apt-fast -y install vlc

#### kdenlive - CAREFULL, a lot of kde packages
#sudo add-apt-repository -y ppa:sunab/kdenlive-svn
#sudo apt-fast -y update
#sudo apt-fast -y install kdenlive

#### natron
#https://natron.inria.fr/
wget http://skylink.dl.sourceforge.net/project/natron/Natron_Linux_x86_64bits_v1.1.0.tar.gz
#more...

#### cinelerra
sudo add-apt-repository -y ppa:cinelerra-ppa/ppa
sudo apt-fast -y update
sudo apt-fast -y install cinelerra-cv

#### Popcorn Time
sudo add-apt-repository -y ppa:webupd8team/popcorntime
sudo apt-fast -y update
sudo apt-fast -y install popcorn-time

#### waifu
wget http://www.waifu.ca/waifu-linux64.tar.gz
#more...

#### Various
sudo apt-fast -y install openshot pitivi

####All multimedia content

##best performance on flash
#http://blog.timvalenta.com/2013/01/chromes-fullscreen-flash-performance-is-slow-laggy-and-heartwrenching/

sudo apt-fast -y install non-free-codecs libxine1-ffmpeg gxine mencoder libmpcdec6 libquicktime2 flac faac faad sox ffmpeg2theora libmpeg2-4 uudeview libmpeg3-1 mpeg3-utils mpegdemux liba52-0.7.4-dev mpeg2dec vorbis-tools id3v2 mpg321 mpg123 libflac++6 ffmpeg libmp4v2-2 icedax tagtool easytag id3tool lame libmad0 libjpeg-progs
sudo apt-fast -y install libavcodec-extra libdvdread4 libappindicator1 x264 uudeview
sudo /usr/share/doc/libdvdread4/./install-css.sh
sudo apt-fast -y install gstreamer0.10-ffmpeg gstreamer0.10-fluendo-mp3 gstreamer0.10-gnonlin gstreamer0.10-plugins-bad-multiverse totem gstreamer-dbus-media-service gstreamer-tools
sudo apt-fast -y install gsfonts gsfonts-x11 ttf-liberation ttf-droid ttf-dejavu libdvdcss2 w64codecs

######## Development

##### enigma - http://enigma-dev.org/docs/Wiki/Install:Linux
#more...

##### MakeHuman
wget -q -O- http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -
test -f /etc/apt/sources.list.d/getdeb_apps.list || sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu utopic-getdeb apps" >> /etc/apt/sources.list.d/getdeb_apps.list'
test -f /etc/apt/sources.list.d/getdeb_games.list || sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu utopic-getdeb games" >> /etc/apt/sources.list.d/getdeb_games.list'
sudo apt-fast -y update
sudo apt-fast -y install makehuman

#### ubuntu-make - (new android studio) http://www.webupd8.org/2014/12/ubuntu-developer-tools-center-renamed.html
##Android Studio from web
#RECOMMENDED - TO IMPROVE - https://developer.android.com/sdk/installing/index.html?pkg=studio
wget https://dl.google.com/dl/android/studio/ide-zips/1.0.1/android-studio-ide-135.1641136-linux.zip
unzip android-studio-ide-135.1641136-linux.zip -d /home/usuario/tools/android
sudo /home/usuario/tools/android/android-studio/bin/studio.sh

sudo add-apt-repository -y ppa:ubuntu-desktop/ubuntu-make
sudo apt-fast -y update
sudo apt-fast -y install ubuntu-make
##Android Studio using Ubuntu Make
#sudo umake android
#sudo umake android --remove	#TO REMOVE
##Eclipse using Ubuntu Make
#sudo umake ide eclipse
#sudo umake ide eclipse --remove	#TO REMOVE

#### Wine
sudo add-apt-repository -y ppa:ubuntu-wine/ppa
sudo apt-fast -y update
sudo apt-fast -y install wine1.7
## Wine config
#sudo apt-fast -y install q4wine winetricks
#export WINEPREFIX=prefix32
#export WINEARCH=win32
#winecfg

#### atom
sudo add-apt-repository -y ppa:webupd8team/atom
sudo apt-fast -y update
sudo apt-fast -y install atom

#### sublime-text
#http://www.webupd8.org/2013/07/sublime-text-3-ubuntu-ppa-now-available.html
sudo add-apt-repository -y ppa:webupd8team/sublime-text-3
sudo apt-fast -y update
sudo apt-fast -y install sublime-text-installer

#### Ubuntu phone sdk - With problems
#sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
#sudo add-apt-repository -y ppa:alexey-ivanov/qtcreator - BE CAREFUL
#sudo add-apt-repository -y ppa:canonical-qt5-edgers/qt5-proper - DEPRECATED, NEVER USE
#sudo add-apt-repository -y ppa:ui-toolkit/ppa - DEPRECATED, NEVER USE
#sudo apt-fast -y update
#sudo apt-fast -y install ubuntu-sdk qml
#qtmultimedia5-examples
#sudo apt-fast -y install qtcreator qt5-default - DON'T USE

#### openjdk6
#sudo apt-fast -y install openjdk-6-jre openjdk-6-jdk icedtea-6-plugin

#### openjdk7
#sudo apt-fast -y install openjdk-7-jre openjdk-7-jdk icedtea-7-plugin

#### openjdk8
sudo apt-fast -y install openjdk-8-jre openjdk-8-jdk icedtea-8-plugin

#### Oracle Java 6 7 8
#sudo add-apt-repository -y ppa:webupd8team/java
#sudo apt-fast -y update

#### Oracle Java6
#sudo apt-fast -y install oracle-java6-installer
#sudo apt-fast install oracle-java6-set-default

#### Oracle Java7
#sudo echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
#sudo apt-fast -y install oracle-java7-installer
#sudo update-java-alternatives -s java-7-oracle
#sudo apt-fast install oracle-java7-set-default

#### Oracle Java8
#sudo echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
#sudo apt-fast -y install oracle-java8-installer
#sudo update-java-alternatives -s java-8-oracle
#sudo apt-fast install oracle-java8-set-default

#### Various
#sudo apt-fast -y install ia32-libs lib32asound2		#REMOVED 
sudo apt-fast -y install libcurl3 libc6-i386 lib32z1

sudo apt-fast -y install terminator zenity gtk3-engines-unico octave-zenity
sudo apt-fast -y install vim

#sudo apt-fast -y install ubuntu-developer-tools-center udtc android		#DEPRECATED
sudo apt-fast -y install geany geany-plugin-spellcheck geany-plugin-addons geany-plugin-extrasel
#sudo apt-fast -y install qt4-demos

#sudo apt-fast -y install notepad-qml qtcreator #### Dependencies problem, be careful.
sudo apt-fast -y install mono-complete mono-basic-dbg

######## Web Browsers

#### google-chrome
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
test -f /etc/apt/sources.list.d/google-chrome.list || sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
sudo apt-fast -y update
sudo apt-fast -y install google-chrome-stable

#### Chromium dev & beta channel - Select
sudo add-apt-repository -y ppa:saiarcot895/chromium-dev
sudo add-apt-repository -y ppa:saiarcot895/chromium-beta
sudo apt-fast -y update
sudo apt-fast -y install chromium-browser chromium-browser-l10n

#### PPA for Ubuntu Mozilla Security Team
sudo add-apt-repository -y ppa:ubuntu-mozilla-security/ppa
sudo apt-fast -y update
sudo apt-fast -y install firefox

#### firefox developer edition ( aurora - fx10)
sudo add-apt-repository -y ppa:ubuntu-mozilla-daily/firefox-aurora
sudo apt-fast -y update
sudo apt-fast -y install firefox

#### firefox daily
sudo add-apt-repository -y ppa:ubuntu-mozilla-daily/ppa
sudo apt-fast -y update
sudo apt-fast -y install firefox-trunk

#### Midori
##sudo add-apt-repository -y ppa:midori/ppa
sudo add-apt-repository -y ppa:midori/midori-dev
sudo apt-fast -y update
sudo apt-fast -y install midori

######## Social

##### Facebook Messenger - DEPRECATED!
#sudo add-apt-repository -y ppa:nilarimogard/webupd8
#sudo apt-fast -y update
#sudo apt-fast -y install fbmessenger

##### Skype
#http://www.skype.com/es/download-skype/skype-for-linux/
wget http://download.skype.com/linux/skype-ubuntu-precise_4.3.0.37-1_i386.deb
sudo dpkg -i skype*.deb
rm skype*.deb

#### Hotot - May be in official repo
sudo add-apt-repository -y ppa:jimmyxu/hotot
sudo apt-fast -y update
sudo apt-fast -y install hotot

#### pidgin
sudo add-apt-repository -y ppa:pidgin-developers/ppa
sudo apt-fast -y update
sudo apt-fast -y install pidgin pidgin-plugin-pack pidgin-twitter pidgin-libnotify pidgin-guifications 
##skype - FROM WEB OR http://www.noobslab.com/2014/01/skype-released-new-version-install-in.html

#### telegram-purple
#http://www.webupd8.org/2014/11/add-telegram-support-to-pidgin-with.html
#sudo add-apt-repository -y ppa:nilarimogard/webupd8
#sudo apt-fast -y update
#sudo apt-fast -y install telegram-purple
##sudo apt-fast dist-upgrade

#### Various
sudo apt-fast -y install choqok xchat

######## File Management

#### SpaceFM - problems
#sudo add-apt-repository -y ppa:mati75/lubuntu
#sudo apt-fast -y update
#sudo apt-fast -y install spacefm

#### Thunar
sudo apt-fast -y install thunar thunar-data thunar-volman libthunarx-2-0 thunar-archive-plugin thunar-media-tags-plugin ffmpegthumbnailer
sudo apt-fast -y install xfce4-goodies

#### Various
sudo apt-fast -y install lhasa filezilla mc

######## File Sharing

#### jdownloader
#Recommended v2 BETA http://installer.jdownloader.org/JD2SilentSetup_x64.sh
sudo add-apt-repository -y ppa:jd-team/jdownloader/
sudo apt-fast -y install jdownloader #### recommended to INSTALL v2 BETA
wget http://installer.jdownloader.org/JD2SilentSetup_x64.sh
chmod +rwx JD2SilentSetup_x64.sh
su usuario -c ./JD2SilentSetup_x64.sh
rm JD2SilentSetup_x64.sh

##### qbittorrent
sudo add-apt-repository -y ppa:qbittorrent-team/qbittorrent-stable
sudo apt-fast -y update
sudo apt-fast -y install qbittorrent

##### Vuze
wget -q -O- http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -
test -f /etc/apt/sources.list.d/getdeb_apps.list || sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu utopic-getdeb apps" >> /etc/apt/sources.list.d/getdeb_apps.list'
test -f /etc/apt/sources.list.d/getdeb_games.list || sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu utopic-getdeb games" >> /etc/apt/sources.list.d/getdeb_games.list'
sudo apt-fast -y update
sudo apt-fast -y install vuze

#### Various
sudo apt-fast -y install amule deluge axel

######## News & Books

#### quiterss
sudo add-apt-repository -y ppa:quiterss/quiterss
sudo apt-fast -y update
sudo apt-fast -y install quiterss

#### Various
sudo apt-fast -y install gpodder calibre newsbeuter rssowl

######## Office & Productivity

#### LibreOffice #### not compatible for 14.10
#sudo add-apt-repository -y ppa:libreoffice/ppa
#sudo apt-fast -y update
#sudo apt-fast -y install libreoffice

#### Office web apps
#cd ..
#sudo dpkg -i ./z.extra/microsoft_online_apps.deb

#### Various
sudo apt-fast -y install okular evince lyx rednotebook zim txt2tags poppler-utils pdftk
sudo apt-fast -y install gnucash (python-gnucash) grisbi hombank skrooge abtransfers codeka adempiere (sugarcrm - not in repos)

######## Games

#### Steam Login
sudo add-apt-repository -y ppa:thor27-gmail/steam-desktop
sudo apt-fast -y update
sudo apt-fast -y install steam steam-login

#### 0ad
sudo add-apt-repository -y ppa:wfg/0ad
sudo apt-fast -y update
sudo apt-fast -y install 0ad

#### lutris
#https://lutris.net/games/
wget http://lutris.net/releases/lutris_0.3.6.3_all.deb
sudo dpkg -i lutris*.deb
rm lutris*.deb

#### dustrac
sudo add-apt-repository -y ppa:jussi-lind/dustrac
sudo apt-fast -y update
sudo apt-fast -y install dustrac

#### Various
#sudo apt-fast -y install true-combat-elite
#americas-army:i386
#lincity-ng
#crossover-games crossover-pro
#gamedevelop
#ogs-mahjong ogs-mahjong-music-addon
#sandboxgamemaker
#opencity
#teeworlds
#d2x-rebirth-full d2x-xl-executable
#numptyphysics
#kolf
#neverputt
#maximinigolf
#assaultcube
#sorr
#iconqueru
#hedgewars
#freeminer
#torcs
#vdrift
#trigger-rally
#stuntrally
#speed-dreams
#gweled
#sgt-puzzles
#kulic
#amor macopix-gtk2 oneko

######## Extra

####Upgrading system
#sudo apt-fast -y upgrade

#### Wine example
#wget http://dl.desktop.line.naver.jp/naver/LINE/win/LineInst.exe
#wine LineInst.exe

#### Repairing jdownloader v1 if is necessary
#sudo update-alternatives --config java

#### Various
#sudo apt-fast -y install diodon diodon-plugins
