#!/bin/bash
######## installpackages - Installs packages & necessary repos - script 3

######## Backup & Sync

#### DirSyncPro
sudo mkdir /opt/DirSyncPro
sudo wget http://kent.dl.sourceforge.net/project/directorysync/DirSync%20Pro%20%28stable%29/1.50/DirSyncPro-1.50-Linux.zip -O /opt/DirSyncPro/DirSyncPro-1.50-Linux.zip
sudo wget http://dirsyncpro.org/images/dirsyncpro.png -O /opt/DirSyncPro/dirsyncpro.png
sudo unzip /opt/DirSyncPro/DirSyncPro-1.50-Linux.zip -d /opt/DirSyncPro
sudo rm /opt/DirSyncPro/DirSyncPro-1.50-Linux.zip
sudo chmod +rwx /opt/DirSyncPro/DirSyncPro-1.50-Linux/dirsyncpro.jar

test -f /usr/share/applications/dirsyncpro.desktop || sudo sh -c 'echo "[Desktop Entry]
Type=Application
Name=DirSyncPro
Comment=Sync your files!
Categories=System
Exec=/opt/DirSyncPro/DirSyncPro-1.50-Linux/dirsyncpro.jar
Icon=/opt/DirSyncPro/dirsyncpro.png" >> /usr/share/applications/dirsyncpro.desktop'
##sudo ln -s /opt/DirSyncPro/DirSyncPro-1.50-Linux/dirsyncpro.jar ~/Escritorio/DirSyncPro

#### systemback
sudo apt-add-repository -y ppa:nemh/systemback
sudo apt-fast -y update
sudo apt-fast -y install systemback

#### TimeShift
#http://www.howtogeek.com/206491/how-to-restore-your-ubuntu-linux-system-to-its-previous-state/
#sudo add-apt-repository -y ppa:teejee2008/ppa
#sudo apt-fast -y update
#sudo apt-fast -y install timeshift

#### syncthing - OUTDATED
#sudo add-apt-repository -y ppa:ytvwld/syncthing
#sudo apt-fast -y update
#sudo apt-fast -y install syncthing

#### syncthing-gtk
#sudo add-apt-repository -y ppa:nilarimogard/webupd8
#sudo apt-fast -y update
#sudo apt-fast -y install syncthing-gtk

######## OS & Utilities

#### customizer (u-customizer)
#https://github.com/clearkimura/Customizer
wget https://github.com/clearkimura/Customizer/archive/4.1.1.tar.gz
tar xzvf 4.1.1.tar.gz
sudo apt-fast -y install git build-essential fakeroot make binutils g++ python python-dev python-qt4 pyqt4-dev-tools squashfs-tools xorriso x11-xserver-utils xserver-xephyr qemu-kvm dpkg-dev debhelper qt4-dev-tools qt4-linguist-tools --no-install-recommends
make && sudo make install
sudo customizer-gui

#### gnome-multiwriter
#sudo apt-fast -y install gnome-common yelp-tools libcanberra-gtk3-dev libudisks2-dev gobject-introspection
#cd /tmp
#rm -rf GNOME_MULTI_WRITER*
#wget --no-check-certificate https://github.com/GNOME/gnome-multi-writer/tarball/master -O GNOME_MULTI_WRITER.tar.gz
#tar xzf GNOME_MULTI_WRITER.tar.gz
#cd gnome-multi-writer-GNOME_MULTI_WRITER_*
##execute

#### ubuntu-touch-coreapps
sudo add-apt-repository -y ppa:ubuntu-touch-coreapps-drivers/daily
sudo apt-fast -y update
#sudo apt-fast -y install calendar-app music-app help-app reminders-app ubuntu-clock-app ubuntu-docviewer-app ubuntu-rssreader-app ubuntu-terminal-app ubuntu-weather-app sudoku-app dropping-letters-app

#### pushbullet-indicator
sudo add-apt-repository -y ppa:atareao/atareao
sudo apt-fast -y update
sudo apt-fast -y install pushbullet-indicator

#### albert
sudo apt-add-repository -y ppa:nilarimogard/webupd8
sudo apt-fast -y update
sudo apt-fast -y install albert

#### mutate
sudo apt-add-repository -y ppa:mutate/ppa
sudo apt-fast -y update
sudo apt-fast -y install mutate

#### undistract-me - http://lamiradadelreplicante.com/2015/01/15/undistract-me-nos-avisa-cuando-un-comando-ha-terminado-de-ejecutarse-en-la-terminal/
sudo apt-fast -y install undistract-me

#### appgrid
sudo add-apt-repository -y ppa:appgrid/stable
sudo apt-fast -y update
sudo apt-fast -y install appgrid

#### postinstallerf
## ancient version
#wget -c http://sourceforge.net/projects/postinstaller/files/ubuntu/app-install-data-postinstallerf_1.0-6_all.deb
#wget -c http://sourceforge.net/projects/postinstaller/files/ubuntu/postinstallerf_1.5-13_all.deb
#sudo add-apt-repository -y ppa:webupd8team/y-ppa-manager
#sudo apt-fast -y update
#sudo apt-fast -y install yad packagekit
#sudo dpkg -i app-install-data-postinstallerf_1.0-6_all.deb
#sudo dpkg -i postinstallerf_1.5-13_all.deb
## latest version
wget -c http://sourceforge.net/projects/postinstaller/files/ubuntu/app-install-data-postinstallerf_1.0-6_all.deb
wget -c http://sourceforge.net/projects/postinstaller/files/fedora/releases/21/x86_64/postinstallerf-1.5-21.fc21.noarch.rpm
sudo add-apt-repository -y ppa:webupd8team/y-ppa-manager
sudo apt-fast -y update
sudo apt-fast -y install yad packagekit
sudo dpkg -i app-install-data-postinstallerf_1.0-6_all.deb
sudo apt-fast -y install alien dpkg-dev debhelper build-essential
sudo alien postinstallerf-1.5-21.fc21.noarch.rpm
sudo dpkg -i postinstallerf_1.5-22_all.deb

#### variety-peterlevi
#sudo add-apt-repository -y ppa:peterlevi/ppa
#sudo add-apt-repository -y ppa:variety/next
sudo add-apt-repository -y ppa:variety/daily
sudo apt-fast -y update
sudo apt-fast -y install variety

#### HP
sudo apt-fast -y install hplip hplip-gui

#### Bible Time!
sudo add-apt-repository -y ppa:unit193/crosswire
sudo apt-fast -y update
sudo apt-fast -y install xiphos bibletime #sword biblesync

#### Various
sudo apt-fast -y install uck	#ubuntu customization kit

######## Desktop Environment

#

######## Themes

#### folder-color
sudo add-apt-repository -y ppa:costales/folder-color
sudo apt-fast -y update
#### nautilus
#sudo apt-fast -y install folder-color
#nautilus -q
#### nemo
#sudo apt-fast -y install folder-color-nemo
#nemo -q
#### caja
sudo apt-fast -y install folder-color-caja
caja -q
#fix if proceed
sudo ln -s /usr/lib/x86_64-linux-gnu/girepository-1.0/Caja-2.0.typelib /usr/lib/girepository-1.0/Caja-2.0.typelib
caja -q

######## Language packages

#

######## Security & Privacy

#

######## CD/DVD Tools

#

######## Photos & Graphics

#

######## Audio & Music

#### pogo
sudo add-apt-repository -y ppa:pogo-dev/stable
sudo apt-fast -y update
sudo apt-fast -y install pogo

######## Videos & Movies

#### shotcut
#http://media-opensource.blogspot.com.es/2015/04/install-shotcut-1504-video-editor-on.html
#https://www.youtube.com/watch?v=cNGILOoadX0
wget https://github.com/mltframework/shotcut/releases/download/v15.06/shotcut-debian7-x86_64-150601.tar.bz2
tar -xjvf shotcut-debian7-x86_64-150601.tar.bz2
sudo rm -rf /home/usuario/Shotcut
sudo mv Shotcut /home/usuario

######## All multimedia content

#

######## Development

#### ubuntu-emulator
#http://www.webupd8.org/2014/03/ubuntu-touch-emulator-installation-and.html
#http://www.webupd8.org/2013/11/experimental-ubuntu-touch-emulator.html
sudo apt-fast -y install ubuntu-emulator

##### Fritzing
wget -q -O- http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -
test -f /etc/apt/sources.list.d/getdeb_apps.list || sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu utopic-getdeb apps" >> /etc/apt/sources.list.d/getdeb_apps.list'
test -f /etc/apt/sources.list.d/getdeb_games.list || sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu utopic-getdeb games" >> /etc/apt/sources.list.d/getdeb_games.list'
sudo apt-fast -y update
sudo apt-fast -y install fritzing

######## Web Browsers

#### i2p
sudo add-apt-repository -y ppa:i2p-maintainers/i2p
sudo apt-fast -y update
sudo apt-fast -y install i2p i2p-router i2pd
#i2prouter start
#http://localhost:7657

######## Social

#

######## File Management

#

######## File Sharing

#

######## News & Books

#

######## Office & Productivity

#### geary
sudo add-apt-repository -y ppa:yorba/daily-builds
sudo apt-fast -y update
sudo apt-fast -y install geary

#### evolution
sudo add-apt-repository -y ppa:fta/gnome3
sudo apt-fast -y update
sudo apt-fast -y install evolution

#### claws-mail
sudo add-apt-repository -y ppa:claws-mail/ppa
sudo apt-fast -y update
sudo apt-fast -y install claws-mail claws-mail-extra-plugins

######## Games

#### Various
sudo apt-fast -y install scourge violetland bofh csmash cdogs-sdl djl
