#!/bin/bash
######## installpackages - Installs packages & necessary repos - script 1

#### Remove all your repos
#sudo rm -f -r /etc/apt/sources.list.d/*

#### Upgrading system
#sudo apt-get -y update
#sudo apt-get -y upgrade
##sudo apt-get -y dist-upgrade

######## Backup & Sync

#

######## OS & Utilities

#### apt-fast
#http://www.atareao.es/ubuntu/liberado-apt-fast-1-6-6-con-configuracion-y-desde-ppa-oficial/
#http://www.atareao.es/ubuntu/instalar-desde-el-terminal-a-velocidad-de-vertigo-con-apt-fast/
##sudo add-apt-repository -y ppa:apt-fast/stable
sudo add-apt-repository -y ppa:saiarcot895/myppa
sudo apt-get -y update
sudo apt-get -y install apt-fast

#### y-ppa-manager - (launchpad getkeys + missing gpg-keys + gpg badsig errors)
sudo add-apt-repository -y ppa:webupd8team/y-ppa-manager
sudo apt-fast -y update
sudo apt-fast -y install y-ppa-manager

#### Getdeb (1)
wget http://archive.getdeb.net/install_deb/getdeb-repository_0.1-1~getdeb1_all.deb &&
wget http://archive.getdeb.net/install_deb/playdeb_0.3-1~getdeb1_all.deb &&
sudo dpkg -i getdeb-repository_0.1-1~getdeb1_all.deb &&
sudo dpkg -i playdeb_0.3-1~getdeb1_all.deb &&
rm -f getdeb-repository_0.1-1~getdeb1_all.deb &&
rm -f playdeb_0.3-1~getdeb1_all.deb

#### Getdeb (2)
#wget -q -O- http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -
#test -f /etc/apt/sources.list.d/getdeb_apps.list || sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu utopic-getdeb apps" >> /etc/apt/sources.list.d/getdeb_apps.list'
#test -f /etc/apt/sources.list.d/getdeb_games.list || sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu utopic-getdeb games" >> /etc/apt/sources.list.d/getdeb_games.list'
#sudo apt-fast -y update

#### mtp support
#sudo add-apt-repository -y ppa:langdalepl/gvfs-mtp
#sudo apt-fast -y update & dist-upgrade
sudo apt-fast -y install mtp-tools mtpfs

#### Various
sudo apt-fast -y install ubuntu-restricted-extras ttf-ancient-fonts synaptic preload prelink gdebi ppa-purge gnome-disk-utility gparted

######## Desktop Environment

#

######## Themes

#### vibrancy-colors icon theme
sudo add-apt-repository -y ppa:ravefinity-project/ppa
sudo apt-fast -y update
sudo apt-fast install vibrancy-colors

######## Language packages
#sudo apt-fast -y install myspell-es wspanish language-pack-es language-pack-es-base 
#sudo apt-fast -y install myspell-en-gb myspell-en-us
sudo apt-fast -y install aspell aspell-en aspell-es

######## Security & Privacy

#### Various
sudo apt-fast -y install gufw mate-tweak

######## CD/DVD Tools

#

######## Photos & Graphics

#### Various
sudo apt-fast -y install gnome-exe-thumbnailer shutter

#### gimp
#sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp-edge
sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp
sudo apt-fast -y update
sudo apt-fast -y install gimp gimp-plugin-registry

#### krita
#http://xubuntugeek.blogspot.com.es/2013/12/how-to-install-lastest-krita-in-xubuntu.html
#http://dimula73.blogspot.com.es/2013/05/krita-lime-ppa-always-fresh-versions.html
sudo add-apt-repository -y ppa:dimula73/krita		# bleeding edge build
sudo apt-fast -y update
sudo apt-fast -y install krita-testing krita-testing-dbg krita-testing-l10n
#sudo restart lightdm
#to execute run "krita"
#sudo apt-fast -y install krita kde-l10n-es calligra-l10n-es	# official
#sudo add-apt-repository ppa:kubuntu-ppa/backports		# another method
#sudo apt-fast update
#sudo apt-fast install krita kritasketch

######## Audio & Music

#

######## Videos & Movies

#

######## All multimedia content

#### ffmpeg
#sudo add-apt-repository -y ppa:kirillshkrogalev/ffmpeg-next
#sudo apt-fast -y update
sudo apt-fast -y install ffmpeg

#### Various

####vlc
sudo add-apt-repository -y ppa:videolan/stable-daily
sudo apt-fast -y update
sudo apt-fast -y install vlc vlc-plugin-pulse libvlc5

######## Development

#### Various

####openjdk-8
#sudo add-apt-repository -y ppa:maarten-fonville/ppa
sudo add-apt-repository -y ppa:mamarley/updates
sudo apt-fast -y update
sudo apt-fast -y install icedtea-8-plugin openjdk-8-jre #icedtea-7-plugin openjdk-7-jre icedtea-9-plugin openjdk-9-jre

######## Web Browsers

#### google-chrome
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
test -f /etc/apt/sources.list.d/google-chrome.list || sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
sudo apt-fast -y update
sudo apt-fast -y install google-chrome-stable

#### google-chrome-unstable
#wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
#test -f /etc/apt/sources.list.d/google-chrome-unstable.list || sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome-unstable.list'
#sudo apt-fast -y update
#sudo apt-fast -y install google-chrome-unstable

#### chromium
#sudo apt-fast -y install chromium-browser chromium-browser-l10n

#### pepper-flash - for chromium
##pepper-flash-player from official repos
##http://www.webupd8.org/2014/01/pepper-flash-player-installer-for.html
#sudo apt-fast -y install pepperflashplugin-nonfree
##sudo update-pepperflashplugin-nonfree --install
##sudo update-pepperflashplugin-nonfree --uninstall - TO UNINSTALL

#### pepper-flash - for chromium (2)
#https://launchpad.net/~skunk/+archive/ubuntu/pepper-flash
#sudo add-apt-repository -y ppa:skunk/pepper-flash
#sudo apt-fast -y update
#sudo apt-fast -y install pepflashplugin-nonfree
#/etc/chromium-browser/default
#. /usr/lib/pepflashplugin-installer/pepflashplayer.sh
#chromium restart

#### pepper-flash - for firefox
#sudo add-apt-repository -y ppa:nilarimogard/webupd8
#sudo apt-fast -y update
#sudo apt-fast -y install pepperflashplugin-nonfree freshplayerplugin

######## Social

#

######## File Management

#### Various
sudo apt-fast -y install rar unrar unace p7zip-full p7zip-rar sharutils mpack arj cabextract		#p7zip

######## File Sharing

#

######## News & Books

#

######## Office & Productivity

#### libreoffice
#sudo add-apt-repository -y ppa:libreoffice/libreoffice-4-4
sudo add-apt-repository -y ppa:libreoffice/libreoffice-prereleases
sudo add-apt-repository -y ppa:libreoffice/ppa
sudo apt-fast -y update
sudo apt-fast -y install libreoffice libreoffice-help-es libreoffice-l10n-es

######## Games

#

######## Extra

#### uninstallpackages
sudo apt-fast -y remove firefox firefox-locale-es firefox-locale-en xul-ext-ubufox pidgin* thunderbird* adobe-flashplugin flashplugin-nonfree-extrasound flashplugin-installer shotwell

#### Upgrading system
#sudo apt-get -y upgrade
#sudo apt-get -y dist-upgrade

#### Repairing system 2/2
#sudo apt-get -f install

#### Cleaning system
#sudo apt-get -f install
sudo apt-get -y autoremove
#sudo apt-get -y autoclean
#sudo apt-get -y clean
