#!/bin/bash
######## installpackages - Installs packages & necessary repos - script 2

######## Backup & Sync

#### freefilesync
sudo apt-fast -y install freefilesync

#### dropbox
apps2/dropbox

#### megasync - personal
#apps2/megasync

######## OS & Utilities

#### teamviewer
apps2/teamviewer

#### converseen
apps2/converseen

#### synapse
apps2/synapse

#### grub-customizer
apps2/grub-customizer

#### bleachbit
sudo apt-fast -y install bleachbit

#### clipit
apps2/clipit

#### screenfetch
sudo apt-fast -y install screenfetch

#### ANGRYsearch
#apps2/ANGRYsearch

#### i-nex - http://i-nex.linux.pl/install/ - https://launchpad.net/i-nex/+download
apps2/i-nex

#### fish-shell
#apps2/fish-shell

#### furiusisomount
#sudo apt-fast -y install furiusisomount

#### ddrescue-gui
#apps2/ddrescue-gui

#### unetbootin
#apps2/unetbootin

######## Desktop Environment

#

######## Themes

#

######## Language packages

#sudo apt-fast -y install myspell-es wspanish language-pack-es language-pack-es-base 
#sudo apt-fast -y install myspell-en-gb myspell-en-us

######## Security & Privacy

#

######## CD/DVD Tools

#

######## Photos & Graphics

#

######## Audio & Music

#### qmmp
apps2/qmmp

######## Videos & Movies

#### sopcast
#apps2/sopcast

#### smplayer + mpv support
#apps2/smplayer

#### handbrake
#sudo apt-fast -y install handbrake

######## Development

#### meld
sudo apt-fast -y install meld

#### Dev Utils
sudo apt-fast -y install build-essential packaging-dev checkinstall cdbs devscripts dh-make fakeroot libxml-parser-perl check avahi-daemon automake make dpatch patchutils autotools-dev debhelper quilt xutils lintian cmake libtool autoconf git git-core subversion bzr ant fastjar gawk gcc gdb ssh-askpass

#### git-stable - personal
#apps2/git-stable

#### smartgit - personal
#apps2/smartgit

#### flatpak
#apps2/flatpak

#### dia
#apps2/dia

#### blender
#apps2/blender

#### fritzing
#apps2/fritzing

#### uecide
#apps2/uecide

#### arduino-ide
#apps2/arduino-ide

#### arduino-studio
#apps2/arduino-studio

#### git-rc
#apps2/git-rc

#### git-gui
#sudo apt-fast -y install git-gui #git-cola qgit 

#### Qt-Linux
#apps2/Qt-Linux

#### kicad
#apps2/kicad

######## Web Browsers

#### tor-browser
#apps2/tor-browser

######## Social

#### skype
#apps2/skype

##### mumble
#apps2/mumble

##### telegram - http://deshack.net/install-telegram-for-linux-as-an-application/ - personal
#apps2/telegram

##### Facebook-Messenger-Desktop - personal
#apps2/Facebook-Messenger-Desktop

##### Whatsie - personal
#apps2/Whatsie

######## File Management

#

######## File Sharing

#### peerflix - personal
#apps2/peerflix

#### samba
##sudo smbpasswd -a usuario
#sudo apt-fast -y install samba system-config-samba cifs-utils caja-share #winbind
#sudo touch /etc/libuser.conf	#fixes a bug

######## News & Books

#

######## Office & Productivity

##### Thunderbird-nightly
#apps2/thunderbird-nightly

######## Games

##### steam
#apps2/steam
