#!/bin/bash
####ubuntupackages v2014.03.12 alpha
########installpackages

sudo apt-get -y update
sudo apt-get -y upgrade

####Backup & Sync
sudo apt-get -y install systemback
#sudo apt-get -y install backintime-gnome sbackup-plugins-fuse grsync

####OS & Utilities
sudo apt-get -y install y-ppa-manager hplip ubuntu-restricted-extras winusb
#sudo apt-get -y install i-nex
#sudo apt-get -y install laptop-mode-tools - NOT FOR 13.10 - gksu lmt-config-gui - This to launch it
#sudo apt-get -y install gparted grub-customizer libfile-mimeinfo-perl catfish bleachbit
#sudo apt-get -y install qtnx unetbootin usb-imagewriter gddrescue testdisk variety baobab gsmartcontrol calendar-indicator
#sudo apt-get -y install xscreensaver-gl xscreensaver-gl-extra
#sudo apt-get -y install alarm-clock gmrun jupiter lm-sensors psensor conky tmux xbindkeys xbindkeys-config htop pcmanfm
#sudo apt-get -y install hplip-gui
#sudo apt-get -y install app-install-data-medibuntu apport-hooks-medibuntu	#### DISCONTINUED

####Language packages
sudo apt-get -y install myspell-es wspanish language-pack-es language-pack-es-base 
#sudo apt-get -y install myspell-en-gb myspell-en-us
#sudo apt-get -y install aspell aspell-en aspell-es

####Security & Privacy
#sudo apt-get -y install gufw seahorse tor-browser

####CD/DVD Tools
#sudo apt-get -y install furiusisomount devede isomaster k3b acetoneiso 

####Photos & Graphics
sudo apt-get -y install shotwell gthumb photo xnviewmp gnome-exe-thumbnailer shutter gimp 
#sudo apt-get -y install inkscape scribus gwenview xsane

####Audio & Music
#sudo apt-get -y install sound-juicer spotify-client audacity mixxx

####Videos & Movies
sudo apt-get -y install kazam
#sudo apt-get -y install openshot

####Audio & Music & Videos & Movies
sudo apt-get -y install vlc

#sudo apt-get -y pepflashplugin-installer - http://www.webupd8.org/2013/04/install-pepper-flash-player-for.html - steps
#sudo sh -c 'echo ". /usr/lib/pepflashplugin-installer/pepflashplayer.sh" >> /etc/chromium-browser/default'

sudo apt-get -y install non-free-codecs libxine1-ffmpeg gxine mencoder libmpcdec6 libquicktime2 flac faac faad sox ffmpeg2theora libmpeg2-4 uudeview libmpeg3-1 mpeg3-utils mpegdemux liba52-0.7.4-dev mpeg2dec vorbis-tools id3v2 mpg321 mpg123 libflac++6 ffmpeg libmp4v2-2 icedax tagtool easytag id3tool lame libmad0 libjpeg-progs
sudo apt-get -y install gstreamer0.10-ffmpeg gstreamer0.10-fluendo-mp3 gstreamer0.10-gnonlin gstreamer0.10-plugins-bad-multiverse totem gstreamer-dbus-media-service gstreamer-tools
sudo apt-get -y install gsfonts gsfonts-x11 ttf-liberation ttf-droid ttf-dejavu libdvdcss2 w64codecs

####Development
sudo apt-get -y install ia32-libs libcurl3 libc6-i386 lib32asound2 lib32z1
sudo apt-get -y install geany geany-plugin-spellcheck geany-plugin-addons geany-plugin-extrasel
sudo apt-get -y install meld vim
#sudo apt-get -y install virtualbox-4.3 wine playonlinux
#sudo apt-get -y install mono-complete mono-basic-dbg
#sudo apt-get -y install build-essential checkinstall cdbs devscripts dh-make fakeroot libxml-parser-perl check avahi-daemon automake make dpatch patchutils autotools-dev debhelper quilt xutils lintian cmake libtool autoconf git git-core subversion bzr ant fastjar gawk gcc

##openjdk7
sudo apt-get -y install openjdk-7-jre openjdk-7-jdk icedtea-7-plugin

##Oracle Java6 u 8
#sudo apt-get -y install oracle-java6-installer

##Oracle Java7
#sudo echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
#sudo apt-get -y install oracle-java7-installer
#sudo update-java-alternatives -s java-7-oracle

##Oracle Java8
#sudo apt-get -y install oracle-java8-installer

####Web Browsers
#sudo apt-get -y install google-chrome-unstable

####Social
#sudo apt-get -y install choqok skype hotot xchat pidgin-plugin-pack pidgin-twitter pidgin-libnotify pidgin-guifications 
#wget http://dl.desktop.line.naver.jp/naver/LINE/win/LineInst.exe
#wine LineInst.exe

####File Management
sudo apt-get -y install rar unrar unace p7zip-full p7zip-rar sharutils mpack lha arj cabextract
sudo apt-get -y install filezilla
#sudo apt-get -y install spacefm mc
##Thunar
#sudo apt-get -y install thunar thunar-data thunar-volman libthunarx-2-0 thunar-archive-plugin thunar-media-tags-plugin ffmpegthumbnailer
#sudo apt-get -y install xfce4-goodies

####File Sharing
#sudo apt-get -y install jdownloader #### recommended to INSTALL v2 BETA
#sudo apt-get -y install amule deluge axel

####News & Books
#sudo apt-get -y install gpodder calibre newsbeuter rssowl

####Office & Productivity
sudo apt-get -y install libreoffice libreoffice-help-es libreoffice-l10n-es okular
#sudo apt-get -y install evince lyx rednotebook zim txt2tags poppler-utils pdftk

####Games
#sudo apt-get -y install steam steam-login
#sudo apt-get -y install 0ad true-combat-elite americas-army:i386 lincity-ng crossover-games crossover-pro gamedevelop djl ogs-mahjong ogs-mahjong-music-addon sandboxgamemaker opencity teeworlds d2x-rebirth-full d2x-xl-executable numptyphysics violetland kolf neverputt maximinigolf assaultcube sorr iconqueru hedgewars

####Extra

##Upgrading system
#sudo apt-get -y upgrade

##Repairing jdownloader v1 if is necessary
#sudo update-alternatives --config java

##ONLY FOR UBUNTU WITH UNITY SURELY

sudo apt-get -y install ubuntu-tweak classicmenu-indicator unity-tweak-tool
#sudo apt-get -y install appgrid unsettings indicator-multiload indicator-cpufreq my-weather-indicator 
#sudo apt-get -y install diodon diodon-plugins

#### ONLY FOR KUBUNTU

#sudo apt-get -y install muon

########installpackagesproblematic

####General packages
#sudo apt-get -y install unity-reboot
#sudo apt-get -y install acroread-common acroread acroread-fonts
#sudo apt-get -y install aptoncd multisystem remastersys remastersys-gui ubiquity-frontend-gtk ubiquity-slideshow-lubuntu bootchart 
#sudo apt-get -y install blender e17 gadmin-rsync mate-core mate-desktop-environment
#sudo apt-get -y install mounty ddrescue  #### NEED TO ADD PPA
#sudo apt-get -y install eog eog-plugins

####Compiz + Cairo-dock + Emerald
#sudo apt-get -y install compizconfig-settings-manager compiz fusion-icon compiz-plugins
#sudo apt-get -y install cairo-dock cairo-dock-plug-ins-data cairo-dock-plug-ins cairo-dock-data cairo-dock-core cairo-dock-plug-ins-integration cairo-dock-plug-ins-dbus-interface-python libgldi3
#sudo apt-get -y install emerald 
#sudo apt-get -y install metacity

####Not free codecs
#sudo apt-get -y install nautilus-script-audio-convert flashplugin-nonfree-extrasound:i386 icedtea-plugin w32codecs

####ERROR
#sudo apt-get -y install quickly quickly-widgets
#suuuujdo apt-get -y install python-snippets acire libvte-2.90-dev libvte-dev python-vte desktopcouch  #### ERROR

####PROBLEMS
#sudo apt-get -y install cairo-compmgr cairo-compmgr-plugins  #### POSSIBLY DEPENDENCIES ERROR
#sudo apt-get -y install mountmanager ntfsprogs  #### ERROR
#sudo apt-get -y install wally wallch


########uninstallpackages

####Possibly needless programs
#sudo apt-get -y remove openjdk-6-jre openjdk-6-jdk icedtea-6-plugin

#### ONLY FOR LUBUNTU

#sudo apt-get remove -y chromium-browser firefox
#sudo apt-get remove -y abiword-common abiword libabiword-2.9 sylpheed sylpheed-plugins sylpheed-doc sylpheed-i18n gnumeric-common gnumeric xpad mtpaint evince-common evince ace-of-penguins
#sudo apt-get remove -y gxine libxine1 libxine1-x mplayer2
#sudo apt-get remove -y libgmtk0 libgmtk0-data libgmlib0

####Upgrading system
#sudo apt-get -y upgrade

####Cleaning system
#sudo apt-get -y clean
#sudo apt-get -y autoremove
