#!/bin/bash
######## installpackages - Installs packages & necessary repos - script 2

######## Backup & Sync

#### backintime testing
sudo add-apt-repository -y ppa:bit-team/testing
sudo apt-fast -y update
#sudo apt-fast -y install backintime-gnome
sudo apt-fast -y install backintime-qt4

#### Unstable synaptic, guake...
sudo add-apt-repository -y ppa:webupd8team/unstable
sudo apt-fast -y update
sudo apt-fast -y install synaptic guake

#### megasync
#test -f /etc/apt/sources.list.d/megasync.list || sudo sh -c 'echo "deb http://mega.nz/linux/MEGAsync/xUbuntu_15.04/ ./" >> /etc/apt/sources.list.d/megasync.list'
#sudo apt-fast -y update
#sudo apt-fast -y install megasync

#add at boot
#mkdir ~/.config/autostart
#rm ~/.config/autostart/megasync.desktop
#test -f ~/.config/autostart/megasync.desktop || sh -c 'echo "[Desktop Entry]
#Type=Application
#Exec=/home/usuario/.megasync/megasync
#Hidden=false
#X-MATE-Autostart-enabled=true
#Name[es_ES]=megasync
#Name=megasync
#Comment[es_ES]=
#Comment=" >> ~/.config/autostart/megasync.desktop'

#mkdir ~/.megasync
#rm ~/.megasync/megasync.sh
#test -f ~/.megasync/megasync.sh || sh -c 'echo "#!/bin/bash

#https://www.reddit.com/r/MEGA/comments/323bti/megasyncno_icon/

#sleep 30
#megasync &" >> ~/.megasync/megasync.sh'

#### DirSyncPro
sudo mkdir /opt/DirSyncPro
sudo wget http://kent.dl.sourceforge.net/project/directorysync/DirSync%20Pro%20%28stable%29/1.50/DirSyncPro-1.50-Linux.zip -O /opt/DirSyncPro/DirSyncPro-1.50-Linux.zip
sudo wget http://dirsyncpro.org/images/dirsyncpro.png -O /opt/DirSyncPro/dirsyncpro.png
sudo unzip /opt/DirSyncPro/DirSyncPro-1.50-Linux.zip -d /opt/DirSyncPro
sudo rm /opt/DirSyncPro/DirSyncPro-1.50-Linux.zip
sudo chmod +rwx /opt/DirSyncPro/DirSyncPro-1.50-Linux/dirsyncpro.jar

test -f /usr/share/applications/dirsyncpro.desktop || sudo sh -c 'echo "[Desktop Entry]
Type=Application
Name=DirSyncPro
Comment=Sync your files!
Categories=System
Exec=/opt/DirSyncPro/DirSyncPro-1.50-Linux/dirsyncpro.jar
Icon=/opt/DirSyncPro/dirsyncpro.png" >> /usr/share/applications/dirsyncpro.desktop'
##sudo ln -s /opt/DirSyncPro/DirSyncPro-1.50-Linux/dirsyncpro.jar ~/Escritorio/DirSyncPro

######## OS & Utilities

#### Teamviewer - POSSIBLY ERROR
#http://www.teamviewer.com/es/download/linux.aspx
wget http://download.teamviewer.com/download/teamviewer_i386.deb
sudo dpkg -i teamviewer_i386.deb
rm teamviewer_i386.deb

#### synapse
sudo add-apt-repository -y ppa:synapse-core/testing
sudo apt-fast -y update
sudo apt-fast -y install synapse

#### tlp
sudo add-apt-repository -y ppa:linrunner/tlp
sudo apt-fast -y update
sudo apt-fast -y install tlp tlp-rdw
#sudo tlp start

#### grub-customizer
sudo add-apt-repository -y ppa:danielrichter2007/grub-customizer
sudo apt-fast -y update
sudo apt-fast -y install grub-customizer

#### UNetbootin
#sudo add-apt-repository -y ppa:n-muench/programs-ppa
#sudo apt-fast -y update
#sudo apt-fast -y install unetbootin

#### bleachbit
sudo apt-fast -y install bleachbit

#### clipit
sudo apt-fast -y install clipit

#add at boot
mkdir ~/.config/autostart
rm ~/.config/autostart/clipit.desktop
test -f ~/.config/autostart/clipit.desktop || sh -c 'echo "[Desktop Entry]
Type=Application
Exec=clipit
Hidden=false
X-MATE-Autostart-enabled=true
Name[es_ES]=clipit
Name=clipit
Comment[es_ES]=
Comment=" >> ~/.config/autostart/clipit.desktop'

#### haguichi
sudo add-apt-repository -y ppa:webupd8team/haguichi
sudo apt-fast -y update
sudo apt-fast -y install haguichi

wget https://secure.logmein.com/labs/logmein-hamachi_2.1.0.139-1_amd64.deb
sudo dpkg -i logmein-hamachi_2.1.0.139-1_amd64.deb

######## Desktop Environment

#

######## Themes

#

######## Language packages

#sudo apt-fast -y install myspell-es wspanish language-pack-es language-pack-es-base 
#sudo apt-fast -y install myspell-en-gb myspell-en-us

######## Security & Privacy

#

######## CD/DVD Tools

#

######## Photos & Graphics

#

######## Audio & Music

#

######## Videos & Movies

#

######## Development

#### dia
sudo add-apt-repository -y ppa:dreibh/ppa
sudo apt-fast -y update
sudo apt-fast -y install dia

#### blender
sudo add-apt-repository -y ppa:thomas-schiex/blender
sudo apt-fast -y update
sudo apt-fast -y install blender

#### arduino ide - http://arduino-er.blogspot.com.es/2014/08/arduino-ide-error-avrdude-seropen-cant.html
#1.7.6
#wget http://download.arduino.org/IDE/1.7.6/arduino-1.7.6.org-linux64.tar.xz
#tar -xf arduino-1.7.6.org-linux64.tar.xz
#sudo usermod -a -G dialout usuario
#sudo chmod a+rw /dev/ttyUSB0

#1.6.5
#wget https://www.arduino.cc/download_handler.php?f=/arduino-1.6.5-r5-linux64.tar.xz
#tar -xf arduino-1.6.5-r5-linux64.tar.xz
#sudo usermod -a -G dialout usuario
#sudo chmod a+rw /dev/ttyUSB0

#### git stable
sudo add-apt-repository -y ppa:git-core/ppa
sudo apt-fast -y update
sudo apt-fast -y install git

#### git rc's
#sudo add-apt-repository -y ppa:git-core/candidate
#sudo apt-fast -y update
#sudo apt-fast -y install git

#### git-gui
sudo apt-fast -y install git-gui #git-cola qgit 

#### Qt Linux
####Qt dependencies on installpackages1
#wget http://download.qt-project.org/official_releases/qt/5.4/5.4.0/qt-opensource-linux-x64-5.4.0.run
#chmod +rwx ~/qt-opensource-linux-x64-5.4.0.run
#~/qt-opensource-linux-x64-5.4.0.run
#rm ~/qt-opensource-linux-x64-5.4.0.run

#### kicad
#sudo add-apt-repository -y ppa:js-reynaud/kicad-package-daily-stable
#sudo add-apt-repository -y ppa:adamwolf/kicad-trusty-backports
sudo add-apt-repository -y ppa:js-reynaud/ppa-kicad
sudo apt-fast -y update
sudo apt-fast -y install kicad

#### meld
sudo apt-fast -y install meld

#### Dev Utils
sudo apt-fast -y install build-essential packaging-dev checkinstall cdbs devscripts dh-make fakeroot libxml-parser-perl check avahi-daemon automake make dpatch patchutils autotools-dev debhelper quilt xutils lintian cmake libtool autoconf git git-core subversion bzr ant fastjar gawk gcc gdb ssh-askpass

######## Web Browsers

#### tor-browser
sudo add-apt-repository -y ppa:webupd8team/tor-browser
sudo apt-fast -y update
sudo apt-fast -y install tor-browser

######## Social

##### telegram (1)- http://deshack.net/install-telegram-for-linux-as-an-application/

mkdir /home/usuario/Telegram
wget https://tdesktop.com/linux -O /home/usuario/telegram.tar.xz

wget https://desktop.telegram.org/img/td_logo.png -O /home/usuario/Telegram/td_logo.png
cd /home/usuario
tar -xf telegram.tar.xz

rm /home/usuario/telegram.tar.xz

#add at boot
mkdir ~/.config/autostart
rm ~/.config/autostart/telegram.desktop
test -f ~/.config/autostart/telegram.desktop || sh -c 'echo "[Desktop Entry]
Type=Application
Exec=/home/usuario/Telegram/Telegram -startintray %u
Hidden=false
X-MATE-Autostart-enabled=true
Name[es_ES]=Telegram
Name=Telegram
Comment[es_ES]=
Comment=" >> ~/.config/autostart/telegram.desktop'

##### Facebook-Messenger-Desktop
##https://github.com/Aluxian/Facebook-Messenger-Desktop/releases
wget https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/download/v1.3.3/Messenger_linux64.deb
sudo dpkg -i Messenger_linux64.deb
rm Messenger_linux64.deb

##### WhatsApp-Desktop
wget https://github.com/Aluxian/WhatsApp-Desktop/releases/download/v1.1.0/UnofficialWhatsApp_linux64.deb
sudo dpkg -i UnofficialWhatsApp_linux64.deb
rm UnofficialWhatsApp_linux64.deb
##another way https://rhoconlinux.wordpress.com/2015/06/27/whatsapp-en-ubuntu-como-instalarlo-y-configurarlo-super-facil/
#cd /tmp/ && clear ; wget https://github.com/Aluxian/WhatsApp-Desktop/releases/download/v1.1.0/UnofficialWhatsApp_linux64.deb -O whatsapp.deb && sudo apt-get install gdebi -y ; sudo gdebi -n whatsapp.deb ; cd ; clear

######## File Management

#

######## File Sharing

#### peerflix
#sudo add-apt-repository -y ppa:chris-lea/node.js
#sudo add-apt-repository -y ppa:rwky/nodejs
#sudo apt-fast -y update
sudo apt-fast -y install nodejs npm
sudo npm install -g peerflix
sudo ln -s /usr/bin/nodejs /usr/bin/node	#way 1 - /usr/bin/env: node: No existe el archivo o el directorio
####Changed line #!/usr/bin/env node to #!/usr/bin/nodejs in file /usr/local/lib/node_modules/peerflix/app.js and everything works.		#way 2
##peerflix "magnet url" --vlc
##peerflix "torrent url" --vlc

#### samba
##sudo smbpasswd -a usuario
sudo apt-fast -y install samba system-config-samba cifs-utils caja-share #winbind

######## News & Books

#

######## Office & Productivity

#

######## Games

#### Steam
#http://askubuntu.com/questions/614422/problem-with-installing-steam-on-ubuntu-15-04/614458#614458
sudo apt-fast -y install steam
#to fix bad value error...
#find $HOME/.steam/root/ubuntu12_32/steam-runtime/*/usr/lib/ -name "libstdc++.so.6" -exec mv "{}" "{}.bak" \; -print

#### Steam Login
#http://repo.steampowered.com/steam/archive/precise/steam_latest.deb
sudo add-apt-repository -y ppa:thor27-gmail/steam-desktop
sudo apt-fast -y update
sudo apt-fast -y install steam steam-login

######## Extra

#### uninstallpackages
#

#### Upgrading system
#sudo apt-get -y upgrade
#sudo apt-get -y dist-upgrade

#### Repairing system 2/2
#sudo apt-get -f install

#### Cleaning system
#sudo apt-get -f install
sudo apt-fast -y autoremove
#sudo apt-get -y autoclean
#sudo apt-get -y clean
