#!/bin/bash
######## installpackages - Installs packages & necessary repos - script 2

######## Backup & Sync

#### spideroak
apps4/spideroak

#### backintime-testing
#apps2/backintime-testing

#### megasync
#apps2/megasync

#### DirSyncPro
#apps2/dirsyncpro

######## OS & Utilities

#### ddrescue-gui
#apps2/ddrescue-gui

#### guake
#apps2/guake

#### teamviewer
apps2/teamviewer

#### synapse
apps2/synapse

#### tlp
#apps2/tlp

#### grub-customizer
#apps2/grub-customizer

#### unetbootin
#apps2/unetbootin

#### bleachbit
sudo apt-fast -y install bleachbit

#### clipit
apps2/clipit

#### haguichi
#apps2/haguichi

######## Desktop Environment

#

######## Themes

#

######## Language packages

#sudo apt-fast -y install myspell-es wspanish language-pack-es language-pack-es-base 
#sudo apt-fast -y install myspell-en-gb myspell-en-us

######## Security & Privacy

#

######## CD/DVD Tools

#

######## Photos & Graphics

#

######## Audio & Music

#### qmmp
apps3/qmmp

######## Videos & Movies

#### smplayer + mpv support
#apps2/smplayer

######## Development

#### dia
#apps2/dia

#### blender
#apps2/blender

##### fritzing
#apps2/fritzing

#### uecide
#apps2/uecide

#### arduino-ide
#apps2/arduino-ide

#### arduino-studio
#apps2/arduino-studio

#### git-stable
apps2/git-stable

#### git-rc
#apps2/git-rc

#### git-gui
#sudo apt-fast -y install git-gui #git-cola qgit 

#### smartgit
#apps2/smartgit

#### Qt-Linux
#apps2/Qt-Linux

#### kicad
#apps2/kicad

#### meld
sudo apt-fast -y install meld

#### Dev Utils
sudo apt-fast -y install build-essential packaging-dev checkinstall cdbs devscripts dh-make fakeroot libxml-parser-perl check avahi-daemon automake make dpatch patchutils autotools-dev debhelper quilt xutils lintian cmake libtool autoconf git git-core subversion bzr ant fastjar gawk gcc gdb ssh-askpass

######## Web Browsers

#### tor-browser
#apps2/tor-browser

######## Social

#### skype
apps2/skype

##### mumble
#apps2/mumble

##### qtox
#apps2/qtox

##### utox
#apps2/utox

##### telegram - http://deshack.net/install-telegram-for-linux-as-an-application/
apps2/telegram

##### Facebook-Messenger-Desktop
apps2/Facebook-Messenger-Desktop

##### WhatsApp-Desktop
apps2/WhatsApp-Desktop

######## File Management

#

######## File Sharing

#### peerflix
apps2/peerflix

#### samba
##sudo smbpasswd -a usuario
sudo apt-fast -y install samba system-config-samba cifs-utils caja-share #winbind

######## News & Books

#

######## Office & Productivity

#

######## Games

#

######## Extra

#### uninstallpackages
#

#### Upgrading system
#sudo apt-get -y upgrade
#sudo apt-get -y dist-upgrade

#### Repairing system 2/2
#sudo apt-get -f install

#### Cleaning system
#sudo apt-get -f install
sudo apt-fast -y autoremove
#sudo apt-get -y autoclean
#sudo apt-get -y clean
