#!/bin/bash
######## installpackages - Installs packages & necessary repos - script 5

#### lshw
#sudo apt-fast -y install lshw-gtk

#### conky-manager
#http://bitelia.com/2014/09/administrar-conky-con-conky-manager
sudo add-apt-repository -y ppa:teejee2008/ppa
sudo apt-fast -y update
sudo apt-fast -y install conky-manager
wget http://www.deviantart.com/download/426662366/conky_harmattan_by_zagortenay333-d720use.zip?token=9fd2773e70622067bb63125af9c3565e85317bfe&ts=1411158738 $ unzip conky_harmattan_by_zagortenay333-d720use.zip $ cp -R Harmattan/ ~/.conky

#### clicompanion
#sudo add-apt-repository -y ppa:clicompanion-devs/clicompanion-nightlies
#sudo apt-fast -y update
#sudo apt-fast -y install clicompanion
wget https://launchpad.net/~clicompanion-devs/+archive/ubuntu/clicompanion-nightlies/+files/clicompanion_1.1-6~bzr112%2Bp21~ubuntu12.04.1_all.deb
sudo dpkg -i clicompanion*.deb

#### indicator-usb - tested and fail!
#sudo add-apt-repository -y ppa:yunnxx/gnome3
#sudo apt-fast -y update
#sudo apt-fast -y install indicator-usb

#### photoqt
sudo add-apt-repository -y ppa:samrog131/ppa
sudo apt-fast -y update
sudo apt-fast -y install photoqt

#### power-installer
#sudo add-apt-repository -y ppa:donadigo/power-installer
sudo add-apt-repository -y ppa:elementary-os/daily
sudo apt-fast -y update
sudo apt-fast -y install power-installer

#### kdeconnect
sudo add-apt-repository -y ppa:vikoadi/ppa
sudo apt-fast -y update
sudo apt-fast -y install indicator-kdeconnect kdeconnect

#### Install an RPM Package on Ubuntu Linux
#http://www.howtogeek.com/howto/ubuntu/install-an-rpm-package-on-ubuntu-linux/
#sudo apt-fast -y install alien dpkg-dev debhelper build-essential
#sudo alien packagename.rpm
#sudo dpkg -i packagename.deb

#### sigram		#MATE PROBLEM
sudo add-apt-repository -y ppa:sialan/desktop
sudo apt-fast -y update
sudo apt-fast -y install sigram

#### cutegram		#MATE PROBLEM
sudo add-apt-repository -y ppa:aseman/desktop-apps
sudo apt-fast -y update
sudo apt-fast -y install cutegram libqtelegram

#### touchpad-indicator
sudo add-apt-repository -y ppa:atareao/atareao
sudo apt-fast -y update
sudo apt-fast -y install touchpad-indicator

#### qllauncher
#http://www.webupd8.org/2014/12/qllauncher-quake-live-launcher-for-linux.html
sudo add-apt-repository -y ppa:broken/ppa
sudo apt-fast -y update
sudo apt-fast -y install qllauncher

#### hollywood
sudo apt-add-repository -y ppa:hollywood/ppa
sudo apt-fast -y update
sudo apt-fast -y install hollywood byobu

#### Trojitá
test -f /etc/apt/sources.list.d/trojita.list || sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/jkt-gentoo:/trojita/xUbuntu_14.10/ /' >> /etc/apt/sources.list.d/trojita.list"
wget http://download.opensuse.org/repositories/home:jkt-gentoo:trojita/xUbuntu_14.10/Release.key
sudo apt-key add - < Release.key
sudo apt-fast -y update
sudo apt-fast -y install trojita

#### bum
sudo apt-fast -y install bum

#### thewindowfactory (twf)
#sudo apt-fast -y install thewindowfactory (twf)
 
 
 
 
