#!/bin/bash
####ubuntupackages v 0.1
########################################################installsources

#### Google Linux Software Repositories
wget -q https://dl-ssl.google.com/linux/linux_signing_key.pub -O- | sudo apt-key add -
sudo sh -c 'echo "### THIS FILE IS AUTOMATICALLY CONFIGURED ###
# You may comment out this entry, but any other modifications may be lost.
deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'

#### LibreOffice
sudo add-apt-repository -y ppa:libreoffice/ppa

#### Ubuntu Tweak
sudo add-apt-repository -y ppa:tualatrix/ppa

#### VirtualBox
wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian raring contrib" >> /etc/apt/sources.list.d/virtualbox.list'

#### Wine
sudo add-apt-repository -y ppa:ubuntu-wine/ppa

#### jdownloader
sudo add-apt-repository -y ppa:jd-team/jdownloader/

#### Getdeb - Es de quantal
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com A8A515F046D7E7CF
sudo sh -c 'echo "deb http://mirrors.dotsrc.org/getdeb/ubuntu quantal-getdeb apps" >> /etc/apt/sources.list.d/getdeb_apps.list'
sudo sh -c 'echo "deb http://mirrors.dotsrc.org/getdeb/ubuntu quantal-getdeb games" >> /etc/apt/sources.list.d/getdeb_games.list'

#### grub-customizer
sudo add-apt-repository -y ppa:danielrichter2007/grub-customizer/

#### gimp
sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp/

#### y-ppa-manager - launchpad getkeys
sudo add-apt-repository -y ppa:webupd8team/y-ppa-manager/

#### variety-peterlevi
sudo add-apt-repository -y ppa:peterlevi/ppa

#### spotify
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 94558F59
sudo sh -c 'echo "deb http://repository.spotify.com stable non-free" >> /etc/apt/sources.list.d/spotify.list'

#### VLC
sudo add-apt-repository -y ppa:videolan/stable-daily

#### Agregando key y repo Medibuntu
sudo -E wget --output-document=/etc/apt/sources.list.d/medibuntu.list http://www.medibuntu.org/sources.list.d/$(lsb_release -cs).list
sudo apt-get update
sudo apt-get --yes --quiet --allow-unauthenticated install medibuntu-keyring

#### photo
sudo add-apt-repository -y ppa:samrog131/ppa

#### Gthumb
sudo add-apt-repository -y ppa:webupd8team/gthumb

#### WebUpd8 Unstable: Synaptic
sudo add-apt-repository -y ppa:webupd8team/unstable

#### GNOME3 Extra Apps: Nautilus, etc
sudo add-apt-repository -y ppa:gnome3-team/gnome3

#### MATE Desktop Environment
sudo apt-get --yes --force-yes install mate-archive-keyring
sudo sh -c 'echo "deb http://packages.mate-desktop.org/repo/ubuntu raring main" >> /etc/apt/sources.list.d/MATE.list'

#### Midori
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A69241F1
sudo sh -c 'echo "deb http://ppa.launchpad.net/midori/ppa/ubuntu raring main" >> /etc/apt/sources.list.d/Midori.list'

#### EXTRA

#### PlayOnLinux - PRECISE
#### wget -q "http://deb.playonlinux.com/public.gpg" -O- | sudo apt-key add -
#### sudo wget http://deb.playonlinux.com/playonlinux_precise.list -O /etc/apt/sources.list.d/playonlinux.list

#### remastersys - PRECISE pero lo instalamos
wget -O - http://www.remastersys.com/ubuntu/remastersys.gpg.key | sudo apt-key add -
sudo sh -c 'echo "deb http://www.remastersys.com/ubuntu precise main" >> /etc/apt/sources.list.d/remastersys.list'

#### back in time - YA EN UBUNTU CREO
#### sudo add-apt-repository -y ppa:bit-team/stable/

#### ualinux - PRECISE
#### wget -q -O- http://archive.ualinux.com/ualinux.key | sudo apt-key add -
#### sudo sh -c 'echo "deb http://archive.ualinux.com/ubuntu precise main" >> /etc/apt/sources.list.d/ualinux.list'

#### Kazam - YA EN UBUNTU CREO
#### sudo add-apt-repository -y ppa:kazam-team/unstable-series

#### UNetbootin - YA EN UBUNTU CREO
#### sudo add-apt-repository -y ppa:gezakovacs/ppa

#### Ubuplus - PRECISE
#### sudo add-apt-repository -y ppa:luismtc20/ppa

#### Hotot - YA EN UBUNTU CREO
#### sudo add-apt-repository -y ppa:jimmyxu/hotot

#### X Updates - PRECISE
#### sudo add-apt-repository -y ppa:ubuntu-x-swat/x-updates/

#### Xorg Edgers - DEMASIADO INESTABLE POSIBLEMENTE
#### sudo add-apt-repository -y ppa:xorg-edgers/ppa
#### cómo desinstalar -> sudo ppa-purge xorg-edgers  -> sudo ppa-purge ubuntu-x-swat

#### E17
sudo add-apt-repository -y ppa:hannes-janetzek/enlightenment-svn

#### Unsettings
sudo add-apt-repository -y ppa:diesch/testing

#### WebUpd8: Audacious, unity-reboot, etc
sudo add-apt-repository -y ppa:nilarimogard/webupd8

#### muCommander (unstable)
sudo wget -O - http://apt.mucommander.com/apt.key | sudo apt-key add -
sudo sh -c 'echo "deb http://apt.mucommander.com unstable main non-free contrib " >> /etc/apt/sources.list.d/mucommander.list'

#### multisystem
wget -q http://liveusb.info/multisystem/depot/multisystem.asc -O- | sudo apt-key add -
sudo sh -c 'echo "deb http://liveusb.info/multisystem/depot all main" >> /etc/apt/sources.list.d/multisystem.list'

#### emerald
sudo add-apt-repository -y ppa:brainpower/testing/

#### jupiter
sudo add-apt-repository -y ppa:webupd8team/jupiter

#### cairo-dock
sudo add-apt-repository -y ppa:cairo-dock-team/weekly

#### Audacity
sudo add-apt-repository -y ppa:audacity-team/daily

#### SpaceFM - SUPERPROBLEMA
sudo add-apt-repository -y ppa:mati75/lubuntu

#### Java
sudo add-apt-repository -y ppa:webupd8team/java