#!/bin/bash
######## installpackages - Installs packages & necessary repos - script 2

######## Backup & Sync

#

######## OS & Utilities

#### albert
sudo apt-add-repository -y ppa:nilarimogard/webupd8
sudo apt-get -y update
sudo apt-get -y install albert

#### undistract-me - http://lamiradadelreplicante.com/2015/01/15/undistract-me-nos-avisa-cuando-un-comando-ha-terminado-de-ejecutarse-en-la-terminal/
sudo apt-get -y install undistract-me

#### appgrid
sudo add-apt-repository -y ppa:appgrid/stable
sudo apt-get -y update
sudo apt-get -y install appgrid

#### postinstallerf
## ancient version
#wget -c http://sourceforge.net/projects/postinstaller/files/ubuntu/app-install-data-postinstallerf_1.0-6_all.deb
#wget -c http://sourceforge.net/projects/postinstaller/files/ubuntu/postinstallerf_1.5-13_all.deb
#sudo add-apt-repository -y ppa:webupd8team/y-ppa-manager
#sudo apt-get -y update
#sudo apt-get -y install yad packagekit
#sudo dpkg -i app-install-data-postinstallerf_1.0-6_all.deb
#sudo dpkg -i postinstallerf_1.5-13_all.deb
## latest version
wget -c http://sourceforge.net/projects/postinstaller/files/ubuntu/app-install-data-postinstallerf_1.0-6_all.deb
wget -c http://sourceforge.net/projects/postinstaller/files/fedora/releases/21/x86_64/postinstallerf-1.5-21.fc21.noarch.rpm
sudo add-apt-repository -y ppa:webupd8team/y-ppa-manager
sudo apt-get -y update
sudo apt-get -y install yad packagekit
sudo dpkg -i app-install-data-postinstallerf_1.0-6_all.deb
sudo apt-get -y install alien dpkg-dev debhelper build-essential
sudo alien postinstallerf-1.5-21.fc21.noarch.rpm
sudo dpkg -i postinstallerf_1.5-22_all.deb

#### variety-peterlevi
#sudo add-apt-repository -y ppa:peterlevi/ppa
#sudo add-apt-repository -y ppa:variety/next
sudo add-apt-repository -y ppa:variety/daily
sudo apt-get -y update
sudo apt-get -y install variety

#### HP
#sudo apt-get -y install hplip hplip-gui

#### variety-peterlevi
#sudo add-apt-repository -y ppa:peterlevi/ppa
#sudo add-apt-repository -y ppa:variety/next
sudo add-apt-repository -y ppa:variety/daily
sudo apt-get -y update
sudo apt-get -y install variety

#### Various
sudo apt-get -y install gparted launchy keepassx #thewindowfactory (twf)
#sudo apt-get -y install freefilesync

######## Desktop Environment

#

######## Themes

#

######## Language packages

#

######## Security & Privacy

#

######## CD/DVD Tools

#

######## Photos & Graphics

#### krita
sudo add-apt-repository ppa:kubuntu-ppa/backports
sudo apt-get update
sudo apt-get install krita kritasketch
#http://xubuntugeek.blogspot.com.es/2013/12/how-to-install-lastest-krita-in-xubuntu.html
##sudo add-apt-repository -y ppa:dimula73/krita		# bleeding edge build
##sudo apt-get -y update
##sudo apt-get -y install krita-testing krita-testing-dbg krita-testing-l10n-es
#to execute run "krita"

######## Audio & Music

#

######## Videos & Movies

#

######## All multimedia content

#

######## Development

#### ubuntu-emulator
#http://www.webupd8.org/2014/03/ubuntu-touch-emulator-installation-and.html
#http://www.webupd8.org/2013/11/experimental-ubuntu-touch-emulator.html
sudo apt-get -y install ubuntu-emulator

#### Kicad
sudo add-apt-repository -y ppa:js-reynaud/ppa-kicad
sudo add-apt-repository -y ppa:adamwolf/kicad-testing-daily		#abandoned
sudo apt-get -y update
sudo apt-get -y install kicad

##### Fritzing
wget -q -O- http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -
sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu utopic-getdeb apps" >> /etc/apt/sources.list.d/getdeb_apps.list'
sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu utopic-getdeb games" >> /etc/apt/sources.list.d/getdeb_games.list'
sudo apt-get -y update
sudo apt-get -y install fritzing

######## Web Browsers

#


######## Social

#

######## File Management

#

######## File Sharing

#

######## News & Books

#

######## Office & Productivity

#

######## Games

#### Various
sudo apt-get -y install scourge violetland bofh
