#!/bin/bash

## https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.12.3-bionic

#### qt for bionic
sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.3-bionic

#### get installed ubuntu version

installed=$(lsb_release -sc)

#### changes installed version for repo version
# necessary / real
# launchpad / installed
sudo sed -i "s/bionic/$installed/g" /etc/apt/sources.list.d/*.list
sudo apt-fast -y update
sudo apt-fast -y install qt512base qt512meta

source /opt/qt512/bin/qt512-env.sh