#!/bin/bash

#### apt-fast
#http://www.atareao.es/ubuntu/liberado-apt-fast-1-6-6-con-configuracion-y-desde-ppa-oficial/
#http://www.atareao.es/ubuntu/instalar-desde-el-terminal-a-velocidad-de-vertigo-con-apt-fast/
##sudo add-apt-repository -y ppa:apt-fast/stable
sudo add-apt-repository -y ppa:saiarcot895/myppa

#automated installation

echo debconf apt-fast/maxdownloads string 5 | sudo debconf-set-selections
echo debconf apt-fast/dlflag boolean true | sudo debconf-set-selections
echo debconf apt-fast/aptmanager string apt | sudo debconf-set-selections

#necessary / real
#sudo sed -i 's/zesty/yakkety/g' /etc/apt/sources.list.d/saiarcot895-ubuntu-myppa-zesty.list
sudo apt-get -y update
sudo apt-get -y install apt-fast
#read