#!/bin/bash

#### apt-fast

#automated installation

echo debconf apt-fast/maxdownloads string 5 | sudo debconf-set-selections
echo debconf apt-fast/dlflag boolean true | sudo debconf-set-selections
echo debconf apt-fast/aptmanager string apt | sudo debconf-set-selections

sudo apt-add-repository -y ppa:apt-fast/stable
sudo apt-get -y update
sudo apt-get -y install apt-fast
