#!/bin/bash

##### buka

owner=oguzhaninan
repo=Buka

curl -s https://api.github.com/repos/$owner/$repo/releases/latest \
| grep "browser_download_url.*amd64.deb" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -qi -

sudo gdebi --non-interactive Buka_*.deb
rm Buka_*.deb