#!/bin/bash

#### caja-extensions
sudo add-apt-repository -y ppa:atareao/caja-extensions
sudo apt-fast -y update
#sudo apt-fast -y install caja-500px-uploader
#sudo apt-fast -y install caja-checksum
#sudo apt-fast -y install caja-convert2dxf
#sudo apt-fast -y install caja-convert2gpx
#sudo apt-fast -y install caja-convert2mp3
#sudo apt-fast -y install caja-convert2ogg
#sudo apt-fast -y install caja-convert2svg
#sudo apt-fast -y install caja-copypaste-images
#sudo apt-fast -y install caja-crusher
#sudo apt-fast -y install caja-document-converter
#sudo apt-fast -y install caja-emailit
#sudo apt-fast -y install caja-iconify
#sudo apt-fast -y install caja-imgur-uploader