#!/bin/bash

#### cerebro - http://blog.desdelinux.net/aumentar-la-productividad-en-linux/#

owner=KELiON
repo=cerebro

curl -s https://api.github.com/repos/$owner/$repo/releases/latest \
| grep "browser_download_url.*deb" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -qi -

sudo gdebi --non-interactive cerebro*.deb
rm cerebro*.deb