#!/bin/bash

##### facebook-messenger-desktop

owner=Aluxian
repo=Messenger-for-Desktop

curl -s https://api.github.com/repos/$owner/$repo/releases/latest \
| grep "browser_download_url.*amd64.deb" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -qi -

sudo gdebi --non-interactive messengerfordesktop*.deb
rm messengerfordesktop*.deb