#!/bin/bash

##### hyper-star-wars
wget https://hyper-updates.now.sh/download/linux_deb
sudo gdebi --non-interactive linux_deb
rm linux_deb
sudo npm install -g hpm-cli
sudo hpm install hyper-star-wars