#!/bin/bash

##### hyper-star-wars
wget https://hyper-updates.now.sh/download/linux_deb
sudo gdebi --non-interactive hyper.deb
rm hyper.deb
sudo npm install -g hpm-cli
sudo hpm install hyper-star-wars