#!/bin/bash

#### micro-text-editor
wget https://github.com/zyedidia/micro/releases/download/nightly/micro-1.3.2-dev.18-linux64.tar.gz
tar -xvf micro-1.3.2-dev.18-linux64.tar.gz
cd micro-1.3.2-dev.18
./micro
sudo cp micro /usr/bin
sudo apt-fast -y install xclip