#!/bin/bash

#### playonlinux
#sudo add-apt-repository -y ppa:noobslab/apps
#sudo apt-get -y update
#sudo apt-get -y install playonlinux
wget https://www.playonlinux.com/script_files/PlayOnLinux/4.2.12/PlayOnLinux_4.2.12.deb
sudo gdebi --non-interactive PlayOnLinux*.deb
rm PlayOnLinux*.deb