#!/bin/bash

#### pokemon-terminal - https://github.com/LazoCoder/Pokemon-Terminal
#sudo apt-fast -y install npm
#sudo npm install --global pokemon-terminal

git clone https://github.com/LazoCoder/Pokemon-Terminal $HOME/.Pokemon-Terminal
echo PATH="$HOME/.Pokemon-Terminal:$"PATH"" >> ~/.bash_profile
source ~/.bash_profile