#!/bin/bash

#### qt511 - https://harishnavnit.wordpress.com/2014/03/24/handling-multiple-versions-of-qt/
sudo add-apt-repository -y ppa:beineri/opt-qt-5.11.1-bionic
sudo apt-fast -y update
sudo apt-fast -y install qt511-meta-minimal
#sudo apt-fast -y install qt511-meta-full
