#!/bin/bash

#### qt5ct
sudo add-apt-repository -y ppa:nilarimogard/webupd8
sudo apt-fast -y update
sudo apt-fast -y install qt5ct

#and then...
#http://www.webupd8.org/2015/11/configure-qt5-application-style-icons.html