#!/bin/bash

#### qtcreator
####Qt dependencies on installpackages1
#wget http://download.qt.io/official_releases/qt/5.5/5.5.0/qt-opensource-linux-x64-5.5.0-2.run
#chmod +rwx ~/qt-opensource-linux-x64-5.5.0-2.run
#~/qt-opensource-linux-x64-5.5.0-2.run
#rm ~/qt-opensource-linux-x64-5.5.0-2.run

#### Qt5 dependencies
#http://wiki.qt.io/Qt5_dependencies
sudo apt-fast -y install mesa-common-dev libx11-xcb-dev libglu1-mesa-dev qt5-default