#!/bin/bash

##### ramme

owner=terkelg
repo=ramme

curl -s https://api.github.com/repos/$owner/$repo/releases/latest \
| grep "browser_download_url.*amd64.deb" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -qi -

sudo gdebi --non-interactive Ramme*.deb
rm Ramme*.deb