#!/bin/bash

#### recultis
sudo mkdir ~/.recultis
sudo wget https://github.com/makson96/Recultis/archive/v1.1.0.tar.gz -O ~/.recultis/v1.1.0.tar.gz
cd ~/.recultis
sudo tar -xvf v1.1.0.tar.gz
#cd Recultis-1.1.0
#create desktop link pending, for now create from app