#!/bin/bash

#### resetter

owner=gaining
repo=Resetter

curl -s https://api.github.com/repos/$owner/$repo/releases/latest \
| grep "browser_download_url.*deb" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -qi -

sudo gdebi --non-interactive resetter*.deb
rm resetter*.deb