#!/bin/bash

#### sublime-text
#http://www.webupd8.org/2013/07/sublime-text-3-ubuntu-ppa-now-available.html
#sudo add-apt-repository -y ppa:webupd8team/sublime-text-3
#sudo apt-fast -y update
#sudo apt-fast -y install sublime-text-installer

wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt-fast -y update
sudo apt-fast -y install sublime-text