#!/bin/bash

#### ubunsys

#Installing depending supported or obsolete ubuntu version

if [ `lsb_release -rs` == "20.04" ] || [ `lsb_release -rs` == "19.10" ] || [ `lsb_release -rs` == "19.04" ] || [ `lsb_release -rs` == "18.10" ] || [ `lsb_release -rs` == "18.04" ] || [ `lsb_release -rs` == "17.10" ] || [ `lsb_release -rs` == "17.04" ] || [ `lsb_release -rs` == "16.10" ] || [ `lsb_release -rs` == "16.04" ] | [ `lsb_release -rs` == "15.10" ] || [ `lsb_release -rs` == "15.04" ] || [ `lsb_release -rs` == "14.10" ] ||  [ `lsb_release -rs` == "14.04" ]
then

	#### removes ancient repos

	sudo rm /etc/apt/sources.list.d/adgellida-ubuntu-ubunsys-*.list /etc/apt/sources.list.d/adgellida-ubuntu-ubunsys-*.list.save /etc/apt/sources.list.d/adgellida-ubuntu-ubunsys-obsolete_version.list /etc/apt/sources.list.d/adgellida-ubuntu-ubunsys-obsolete_version.list.save

	#### add ubunsys repo por eoan only

	sudo add-apt-repository -y ppa:adgellida/ubunsys

	#### get installed ubuntu version

	installed=$(lsb_release -sc)

	#### changes installed version for repo version. To get disco version on all ubuntu versions
	# necessary / real
	# launchpad / installed
	sudo sed -i "s/disco/$installed/g" /etc/apt/sources.list.d/adgellida-ubuntu-ubunsys-*.list
	sudo apt-get -y update
	sudo apt-get -y install ubunsys

else
	
	echo "Not an Ubuntu version compatible from 20.04 to 14.04. Not installed"

fi

rm ubunsys*