#!/bin/bash

#### virtualbox
#wget http://download.virtualbox.org/virtualbox/5.1.28/virtualbox-5.1_5.1.28-117968~Ubuntu~zesty_amd64.deb
#sudo gdebi --non-interactive virtualbox-5.1_5.1.28-117968~Ubuntu~zesty_amd64.deb
#rm virtualbox-*.deb

wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
#test -f /etc/apt/sources.list.d/virtualbox.list || sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -sc)  contrib" >> /etc/apt/sources.list.d/virtualbox.list'
test -f /etc/apt/sources.list.d/virtualbox.list || sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian bionic contrib" >> /etc/apt/sources.list.d/virtualbox.list'
sudo sed -i -e 's/deb http/deb [arch=amd64] http/' "/etc/apt/sources.list.d/virtualbox.list"
sudo apt-fast -y update
sudo apt-fast -y install virtualbox-5.2

##Next
#install extension pack
#sudo adduser usuario vboxusers
#shared clipboard
#guest additions

#ancient
#wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
#test -f /etc/apt/sources.list.d/virtualbox.list || sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -sc)  contrib" >> /etc/apt/sources.list.d/virtualbox.list'
#sudo apt-fast -y update
#sudo apt-fast -y install virtualbox-5.0 #virtualbox-4.3 dkms