#!/bin/bash

#### webmin
wget -q -O - http://www.webmin.com/jcameron-key.asc | sudo apt-key add -
test -f /etc/apt/sources.list.d/webmin.list || sudo sh -c 'echo "deb https://download.webmin.com/download/repository sarge contrib" >> /etc/apt/sources.list.d/webmin.list'
sudo apt-fast -y update
sudo apt-fast -y install apt-transport-https webmin