#!/bin/bash

##### whatsapp-desktop

owner=Enrico204
repo=Whatsapp-Desktop

curl -s https://api.github.com/repos/$owner/$repo/releases/latest \
| grep "browser_download_url.*amd64.deb" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -qi -

sudo gdebi --non-interactive whatsapp*.deb
rm whatsapp*.deb