#!/bin/bash

#### krita-testing - recommended
sudo add-apt-repository -y ppa:dimula73/krita
sudo apt-fast -y update
sudo apt-fast -y install krita3-testing krita3-testing-l10n
#sudo mv /usr/share/applications/kde4/krita.desktop /usr/share/applications/