#!/bin/bash

#### kodi-nightly
sudo apt-get install software-properties-common
#sudo add-apt-repository -y ppa:team-xbmc/ppa
#sudo add-apt-repository -y ppa:team-xbmc/unstable
sudo add-apt-repository -y ppa:team-xbmc/xbmc-nightly
sudo apt-fast -y update
sudo apt-fast -y install kodi