#!/bin/bash

#### lightworks
wget http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_6.4.0_all.deb
sudo phoronix-test-suite_6.4.0_all.deb
rm phoronix-test-suite_6.4.0_all.deb