#!/bin/bash

##### vuze

#### getdeb way 1
wget http://archive.getdeb.net/install_deb/getdeb-repository_0.1-1~getdeb1_all.deb
sudo gdebi --non-interactive getdeb-repository_0.1-1~getdeb1_all.deb
rm getdeb-repository_0.1-1~getdeb1_all.deb

sudo apt-fast -y update
sudo apt-fast -y install vuze