#!/bin/bash

#### apt-fast

#automated installation

echo debconf apt-fast/maxdownloads string 5 | sudo debconf-set-selections
echo debconf apt-fast/dlflag boolean true | sudo debconf-set-selections
echo debconf apt-fast/aptmanager string apt | sudo debconf-set-selections


sudo add-apt-repository -y ppa:apt-fast/stable
#real         / compatible
#installed v. / launchpad v.

INSTALLED=$(lsb_release -sc)

sudo sed -i "s/${INSTALLED}/eoan/g" "/etc/apt/sources.list.d/apt-fast-ubuntu-stable-${INSTALLED}.list"
#sudo sed -i 's/focal/eoan/g' '/etc/apt/sources.list.d/apt-fast-ubuntu-stable-focal.list'
sudo apt-get -y update
sudo apt-get -y install apt-fast


###old

#http://www.atareao.es/ubuntu/liberado-apt-fast-1-6-6-con-configuracion-y-desde-ppa-oficial/
#http://www.atareao.es/ubuntu/instalar-desde-el-terminal-a-velocidad-de-vertigo-con-apt-fast/

#sudo add-apt-repository -y ppa:apt-fast/stable
#sudo apt-get -y update
#sudo apt-get -y install apt-fast
#read

#wget https://launchpad.net/~apt-fast/+archive/ubuntu/stable/+files/apt-fast_1.9.8-1~ubuntu19.10.1_all.deb
#sudo gdebi --non-interactive apt-*.deb
#rm apt-*.deb