#!/bin/bash

##### kdiskmark
wget https://github.com/JonMagon/KDiskMark/releases/download/2.0.0/kdiskmark_2.0.0_amd64.deb
sudo gdebi --non-interactive kdiskmark_2.0.0_amd64.deb
rm kdiskmark_2.0.0_amd64.deb
