#!/bin/bash
########configurations

######################Run cairo-dock at startup in compatibility transparency mode with a few window managers - http://glx-dock.org/ww_page.php?p=Recurrents%20problems&lang=en

mkdir ~/.config/autostart
rm ~/.config/autostart/cairo-dock.desktop
sh -c 'echo "[Desktop Entry]
Type=Application
Exec=cairo-dock -W
Hidden=false
X-MATE-Autostart-enabled=true
Name[es_ES]=Cairo Dock
Name=Cairo Dock
Comment[es_ES]=
Comment=" >> ~/.config/autostart/cairo-dock.desktop'

###################################################Add user to group scanner

#sudo adduser usuario scanner

###################################################Disable amazon lens - http://www.webupd8.org/2013/10/how-to-disable-amazon-shopping.html
##Step 1
#Open Dash, go to the Applications lens
#(either do it manually using your mouse or use the Super + A keyboard shortcut),
#click "Filter results" on the right and under "Type", select "Dash plugins".
#All the Dash search plugins (scopes) should be listed

##Step 2
#gsettings set com.canonical.Unity.Lenses disabled-scopes "['more_suggestions-amazon.scope', 'more_suggestions-u1ms.scope', 'more_suggestions-populartracks.scope', 'music-musicstore.scope', 'more_suggestions-ebay.scope', 'more_suggestions-ubuntushop.scope', 'more_suggestions-skimlinks.scope']"

###################################################Enable hibernation - http://tutorfreebr.blogspot.com.es/2013/10/como-ativar-o-modo-de-hibernacao-no.html - http://www.taringa.net/posts/linux/14651627/Activar-funcion-Hibernar-en-Ubuntu-12-04-Precise-Pangoli.html

#sudo sh -c 'echo "

#[Re-enable hibernate by default in upower]
#Identity=unix-user:*
#Action=org.freedesktop.upower.hibernate
#ResultActive=yes

#[Re-enable hibernate by default in logind]
#Identity=unix-user:*
#Action=org.freedesktop.login1.hibernate
#ResultActive=yes

#" >> /etc/polkit-1/localauthority/50-local.d/com.ubuntu.desktop.pkla'

###################################################Enable Progress Fancy in Apt & apt-get - http://www.omgubuntu.co.uk/2014/04/how-to-enable-apt-terminal-progress-bar

#Works
#echo -e 'Dpkg::Progress-Fancy "1";' | sudo tee /etc/apt/apt.conf.d/99progressbar

#Alternative 1
#sudo echo 'Dpkg::Progress-Fancy "1";' > /etc/apt/apt.conf.d/99progressbar

#Alternative 2
##sudo echo 'Dpkg::Progress-Fancy "1";' > /etc/apt/apt.conf/99progressbar
