#!/bin/bash
########installpackages

sudo apt-get -y update
sudo apt-get -y upgrade

####Backup & Sync
sudo apt-get -y install systemback

####OS & Utilities
sudo apt-get -y install ubuntu-restricted-extras synaptic gdebi cairo-dock ppa-purge
#gnome-system-tools gnome-disk-utility

########Desktop Environment
#

########Themes
sudo apt-get -y install ambiance-colors radiance-colors ubuntu-mono

####Language packages
#

####Security & Privacy
#

####CD/DVD Tools
#

####Photos & Graphics
sudo apt-get -y install gnome-exe-thumbnailer shutter gimp xsane

####Audio & Music
#

####Videos & Movies
#

####All multimedia content
sudo apt-get -y install vlc

####Development
sudo apt-get -y install openjdk-7-jre
#ubuntu-sdk geany

#sudo apt-get -y install virtualbox virtualbox-dkms virtualbox-guest-additions-iso virtualbox-guest-utils virtualbox-guest-x11 virtualbox-qt

####Web Browsers
sudo apt-get -y install google-chrome-stable

####Social
#

####File Management
sudo apt-get -y install rar unrar unace p7zip-full p7zip-rar sharutils mpack arj cabextract

####File Sharing
#sudo apt-get -y install jdownloader #### recommended to INSTALL v2 BETA

####News & Books
#

####Office & Productivity
sudo apt-get -y install libreoffice libreoffice-help-es libreoffice-l10n-es ttf-mscorefonts-installer

####Games
#

####Extra

#### TO INSTALL MANUALLY

#http://www.teamviewer.com/es/download/linux.aspx
wget http://download.teamviewer.com/download/teamviewer_linux.deb

#http://www.skype.com/es/download-skype/skype-for-linux/

wget http://download.skype.com/linux/skype-ubuntu-precise_4.3.0.37-1_i386.deb

sudo dpkg -i *.deb

##ONLY FOR UBUNTU WITH UNITY SURELY
#

#### ONLY FOR KUBUNTU
#

########installpackagesproblematic
#

########uninstallpackages
#sudo apt-get remove -y firefox firefox-locale-es firefox-locale-en xul-ext-ubufox

#### ONLY FOR UBUNTU
#sudo apt-get remove -y webbrowser-app
#sudo apt-get remove -y unity-lens* unity-scope*

#### ONLY FOR LUBUNTU
#

####Upgrading system
#sudo apt-get -y upgrade

####Cleaning system
#sudo apt-get -y clean
#sudo apt-get -y autoremove
