#!/bin/bash
########installpackages

####Repairing system 1
sudo apt-get -f install

####Upgrading system
sudo apt-get -y update
sudo apt-get -y upgrade

####Backup & Sync
sudo apt-get -y install systemback

####OS & Utilities
sudo apt-get -y install ubuntu-restricted-extras synaptic gdebi ppa-purge

#cairo-dock #Run cairo-dock at startup in compatibility transparency mode with a few window managers - http://glx-dock.org/ww_page.php?p=Recurrents%20problems&lang=en
sudo apt-get -y install cairo-dock
mkdir ~/.config/autostart
rm ~/.config/autostart/cairo-dock.desktop
sh -c 'echo "[Desktop Entry]
Type=Application
Exec=cairo-dock -W
Hidden=false
X-MATE-Autostart-enabled=true
Name[es_ES]=Cairo Dock
Name=Cairo Dock
Comment[es_ES]=
Comment=" >> ~/.config/autostart/cairo-dock.desktop'

########Desktop Environment
#

########Themes
#

####Language packages
#

####Security & Privacy
sudo apt-get -y install gufw

####CD/DVD Tools
#

####Photos & Graphics
sudo apt-get -y install gnome-exe-thumbnailer shutter gimp xsane

####Audio & Music
#

####Videos & Movies
#

####All multimedia content
sudo apt-get -y install vlc

####Development
sudo apt-get -y install openjdk-7-jre

####Web Browsers
sudo apt-get -y install google-chrome-stable

####Social
#

####File Management
sudo apt-get -y install rar unrar unace p7zip-full p7zip-rar sharutils mpack arj cabextract

####File Sharing
#sudo apt-get -y install jdownloader #### recommended to INSTALL v2 BETA
wget http://installer.jdownloader.org/JD2SilentSetup_x64.sh
chmod +rwx JD2SilentSetup_x64.sh
su usuario -c ./JD2SilentSetup_x64.sh
rm JD2SilentSetup_x64.sh
####News & Books
#

####Office & Productivity
sudo apt-get -y install libreoffice libreoffice-help-es libreoffice-l10n-es ttf-mscorefonts-installer

####Games
#

####Extra

##ONLY FOR UBUNTU WITH UNITY SURELY
#

#### ONLY FOR KUBUNTU
#

########installpackagesproblematic
#

########uninstallpackages
sudo apt-get remove -y firefox firefox-locale-es firefox-locale-en xul-ext-ubufox teamviewer* skype*

#### ONLY FOR LUBUNTU
#

####Upgrading system
sudo apt-get -y upgrade
sudo apt-get -y dist-upgrade

####Repairing system 2
sudo apt-get -f install

####Cleaning system
sudo apt-get -y clean
sudo apt-get -y autoremove

