#!/bin/bash
########installsources

rm -f -r /etc/apt/sources.list.d/*

#### google-chrome
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'

#### gimp
sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp/

#### VLC #### not compatible for 14.10
sudo add-apt-repository -y ppa:ed10vi86/video

#### systemback - HIGHLY RECOMMENDED!
sudo apt-add-repository -y ppa:nemh/systemback

#### LibreOffice #### not compatible for 14.10
sudo add-apt-repository -y ppa:libreoffice/ppa

#### cairo-dock
sudo add-apt-repository -y ppa:cairo-dock-team/weekly
