#!/bin/bash
########installpackages

sudo apt-get -y update
sudo apt-get -y upgrade

####Backup & Sync
sudo apt-get -y install systemback

####OS & Utilities
sudo apt-get -y install ubuntu-restricted-extras synaptic gdebi gnome-system-tools

########Desktop Environment
#

########Themes
#

####Language packages
#

####Security & Privacy
#

####CD/DVD Tools
#

####Photos & Graphics
sudo apt-get -y install gnome-exe-thumbnailer shutter gimp 

####Audio & Music
#

####Videos & Movies
#

####All multimedia content
sudo apt-get -y install vlc

####Development
#

####Web Browsers
sudo apt-get -y install google-chrome-stable

####Social
#

####File Management
sudo apt-get -y install rar unrar unace p7zip-full p7zip-rar sharutils mpack arj cabextract

####File Sharing
#sudo apt-get -y install jdownloader #### recommended to INSTALL v2 BETA

####News & Books
#

####Office & Productivity
sudo apt-get -y install libreoffice libreoffice-help-es libreoffice-l10n-es

####Games
#

####Extra

##ONLY FOR UBUNTU WITH UNITY SURELY
#

#### ONLY FOR KUBUNTU
#

########installpackagesproblematic
#

########uninstallpackages
sudo apt-get remove -y firefox firefox-locale-es firefox-locale-en xul-ext-ubufox

#### ONLY FOR LUBUNTU
#

####Upgrading system
#sudo apt-get -y upgrade

####Cleaning system
#sudo apt-get -y clean
#sudo apt-get -y autoremove
