#!/bin/bash
########installsources

rm -f -r /etc/apt/sources.list.d/*

#### google-chrome
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'

#### gimp
sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp/

#### VLC #### not compatible for 14.10
sudo add-apt-repository -y ppa:ed10vi86/video

#### systemback - HIGHLY RECOMMENDED!
sudo apt-add-repository -y ppa:nemh/systemback

#### LibreOffice #### not compatible for 14.10
sudo add-apt-repository -y ppa:libreoffice/ppa

#### cairo-dock
sudo add-apt-repository -y ppa:cairo-dock-team/weekly

#### ambiance and radiance themes
sudo add-apt-repository -y ppa:ravefinity-project/ppa

#### y-ppa-manager - launchpad getkeys
sudo add-apt-repository -y ppa:webupd8team/y-ppa-manager/

#### grub-customizer
sudo add-apt-repository -y ppa:danielrichter2007/grub-customizer/

#### Xorg Edgers - Unstable - Contains "bleeding-edge" graphics/system packages which may be unstable - more updated than ppa:ubuntu-x-swat/x-updates
sudo add-apt-repository -y ppa:xorg-edgers/ppa
# how to uninstall it -> sudo ppa-purge xorg-edgers  -> sudo ppa-purge ubuntu-x-swat

#### Insync
wget -qO - https://d2t3ff60b2tol4.cloudfront.net/services@insynchq.com.gpg.key | sudo apt-key add -
sudo sh -c 'echo "deb http://apt.insynchq.com/ubuntu trusty non-free contrib" >> /etc/apt/sources.list.d/insync.list'
#referal
#https://www.insynchq.com/r/106908789160316075573

#### Ubuntu phone sdk
#sudo add-apt-repository -y ppa:canonical-qt5-edgers/qt5-proper
#sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
#sudo add-apt-repository -y ppa:alexey-ivanov/qtcreator - BE CAREFUL
########sudo add-apt-repository -y ppa:ui-toolkit/ppa - DEPRECATED, NEVER USE

#### Wine
#sudo add-apt-repository -y ppa:ubuntu-wine/ppa
