#!/bin/bash
######## installpackages - Installs packages & necessary repos

######## Backup & Sync

#

######## OS & Utilities

####conky-manager - http://bitelia.com/2014/09/administrar-conky-con-conky-manager
#sudo add-apt-repository -y ppa:teejee2008/ppa
#sudo apt-get -y update
#sudo apt-get -y install conky-manager
#wget http://www.deviantart.com/download/426662366/conky_harmattan_by_zagortenay333-d720use.zip?token=9fd2773e70622067bb63125af9c3565e85317bfe&ts=1411158738 $ unzip conky_harmattan_by_zagortenay333-d720use.zip $ cp -R Harmattan/ ~/.conky

#### postinstallerf
#wget -c http://sourceforge.net/projects/postinstaller/files/ubuntu/app-install-data-postinstallerf_1.0-6_all.deb
#wget -c http://sourceforge.net/projects/postinstaller/files/ubuntu/postinstallerf_1.5-13_all.deb
#sudo add-apt-repository ppa:webupd8team/y-ppa-manager
#sudo apt-get -y update
#sudo apt-get install yad
#sudo apt-get install packagekit
#dpkg -i app-install-data-postinstallerf_1.0-6_all.deb
#dpkg -i postinstallerf_1.5-13_all.deb

#### apt-fast
#http://www.atareao.es/ubuntu/liberado-apt-fast-1-6-6-con-configuracion-y-desde-ppa-oficial/
#http://www.atareao.es/ubuntu/instalar-desde-el-terminal-a-velocidad-de-vertigo-con-apt-fast/
#sudo add-apt-repository -y ppa:saiarcot895/myppa
#sudo apt-get -y update
#sudo apt-get -y install apt-fast

#### tlp
#sudo add-apt-repository -y ppa:linrunner/tlp
#sudo apt-get -y update
#sudo apt-get -y install tlp tlp-rdw
#sudo tlp start

#### burg - http://www.noobslab.com/2014/09/replace-grub-with-burg-to-beautify-boot.html
#sudo add-apt-repository -y ppa:n-muench/burg
#sudo apt-get -y update
#sudo apt-get -y install burg burg-themes ### After installation you can run burg-emu to choose theme and change resolution (You also can do it while you are in actual BURG). To change themes use F2 and to change resolution use F3
#To revert back to GRUB enter following commands:
#sudo apt-get remove --purge burg burg-themes
#sudo add-apt-repository -r ppa:n-muench/burg
#sudo update-grub

#### clicompanion
#sudo add-apt-repository -y ppa:clicompanion-devs/clicompanion-nightlies
#sudo apt-get -y update
#sudo apt-get -y install clicompanion

#### indicator-usb
#sudo add-apt-repository -y ppa:yunnxx/gnome3
#sudo apt-get -y update
#sudo apt-get -y install indicator-usb

#### ubutricks - http://www.tuxarena.com/apps/ubutricks/
#sudo apt-get -y install zenity gksu
#wget http://www.tuxarena.com/intro/files/ubutricks.sh
#chmod +x ubutricks.sh
#./ubutricks.sh

#### photoqt
#sudo add-apt-repository -y ppa:samrog131/ppa
#sudo apt-get -y update
#sudo apt-get -y install photoqt

#### folder-color
#sudo add-apt-repository -y ppa:costales/folder-color
#sudo apt-get -y update

##nautilus
#sudo apt-get -y install folder-color
#nautilus -q

##nemo
#sudo apt-get -y install folder-color-nemo
#nemo -q

##caja
#sudo apt-get -y install folder-color-caja
#caja -q
#fix if proceed
#sudo ln -s /usr/lib/x86_64-linux-gnu/girepository-1.0/Caja-2.0.typelib /usr/lib/girepository-1.0/Caja-2.0.typelib

##power-installer
#sudo add-apt-repository -y ppa:elementary-os/daily
#sudo add-apt-repository -y ppa:donadigo/power-installer
#sudo apt-get -y update
#sudo apt-get -y install power-installer