#!/bin/bash
########installsources

####conky-manager - http://bitelia.com/2014/09/administrar-conky-con-conky-manager
#sudo add-apt-repository -y ppa:teejee2008/ppa

#### apt-fast
#http://www.atareao.es/ubuntu/liberado-apt-fast-1-6-6-con-configuracion-y-desde-ppa-oficial/
#http://www.atareao.es/ubuntu/instalar-desde-el-terminal-a-velocidad-de-vertigo-con-apt-fast/
#sudo add-apt-repository -y ppa:saiarcot895/myppa

#### tlp
#sudo add-apt-repository -y ppa:linrunner/tlp

#### burg - http://www.noobslab.com/2014/09/replace-grub-with-burg-to-beautify-boot.html
#sudo add-apt-repository -y ppa:n-muench/burg