#!/bin/bash

#### vibrancy-colors icon theme
sudo add-apt-repository -y ppa:ravefinity-project/ppa

#necessary / real
sudo sed -i 's/cosmic/zesty/g' /etc/apt/sources.list.d/ravefinity-project-ubuntu-ppa-yakkety.list
sudo rename 's/cosmic/zesty/g' /etc/apt/sources.list.d/ravefinity-project-ubuntu-ppa-yakkety.list

sudo apt-fast -y update
sudo apt-fast install vibrancy-colors