#!/bin/bash

#### vibrancy-colors icon theme
sudo add-apt-repository -y ppa:ravefinity-project/ppa

#necessary / real
sudo sed -i 's/cosmic/xenial/g' /etc/apt/sources.list.d/ravefinity-project-ubuntu-ppa-cosmic.list
sudo rename 's/cosmic/xenial/g' /etc/apt/sources.list.d/ravefinity-project-ubuntu-ppa-cosmic.list

sudo apt-fast -y update
sudo apt-fast install vibrancy-colors