#!/bin/bash

##### Facebook-Messenger-Desktop
##https://github.com/Aluxian/Facebook-Messenger-Desktop/releases
wget https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/download/v1.5.0-beta.1/Messenger_linux64_V150_beta1.deb
sudo dpkg -i Messenger_linux64.deb
rm Messenger_linux64.deb