#!/bin/bash

##### Facebook-Messenger-Desktop
##https://github.com/Aluxian/Facebook-Messenger-Desktop/releases
wget https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/download/v1.3.3/Messenger_linux64.deb
sudo dpkg -i Messenger_linux64.deb
rm Messenger_linux64.deb