#!/bin/bash

#### megasync
test -f /etc/apt/sources.list.d/megasync.list || sudo sh -c 'echo "deb http://mega.nz/linux/MEGAsync/xUbuntu_15.04/ ./" >> /etc/apt/sources.list.d/megasync.list'
sudo apt-fast -y update
sudo apt-fast -y install megasync

#add at boot
mkdir ~/.config/autostart
rm ~/.config/autostart/megasync.desktop
test -f ~/.config/autostart/megasync.desktop || sh -c 'echo "[Desktop Entry]
Type=Application
Exec=/home/usuario/.megasync/megasync
Hidden=false
X-MATE-Autostart-enabled=true
Name[es_ES]=megasync
Name=megasync
Comment[es_ES]=
Comment=" >> ~/.config/autostart/megasync.desktop'

#mkdir ~/.megasync
#rm ~/.megasync/megasync.sh
#test -f ~/.megasync/megasync.sh || sh -c 'echo "#!/bin/bash

#https://www.reddit.com/r/MEGA/comments/323bti/megasyncno_icon/

#sleep 30
#megasync &" >> ~/.megasync/megasync.sh'