#!/bin/bash

#### peerflix
#sudo add-apt-repository -y ppa:chris-lea/node.js
#sudo add-apt-repository -y ppa:rwky/nodejs
#sudo apt-fast -y update
sudo apt-fast -y install nodejs npm
sudo npm install -g peerflix
sudo ln -s /usr/bin/nodejs /usr/bin/node	#way 1 - /usr/bin/env: node: No existe el archivo o el directorio
####Changed line #!/usr/bin/env node to #!/usr/bin/nodejs in file /usr/local/lib/node_modules/peerflix/app.js and everything works.		#way 2
##peerflix "magnet url" --vlc
##peerflix "torrent url" --vlc