#!/bin/bash

#### thunderbird-stable
#sudo add-apt-repository -y ppa:ubuntu-mozilla-daily/thunderbird-stable
#sudo apt-get -y update
#sudo apt-get -y dist-upgrade
#sudo apt-get -y install thunderbird thunderbird-locale-es

#### thunderbird-next (beta)
sudo add-apt-repository -y ppa:mozillateam/thunderbird-next
sudo apt-get -y update
sudo apt-get -y dist-upgrade
sudo apt-get -y install thunderbird thunderbird-locale-es

#### thunderbird-aurora (aurora) - not working
#sudo add-apt-repository -y ppa:ubuntu-mozilla-daily/thunderbird-aurora
#sudo apt-get -y update
#sudo apt-get -y dist-upgrade
#sudo apt-get -y install thunderbird thunderbird-locale-es

#### thunderbird-trunk (nightly) - not working
#sudo add-apt-repository -y ppa:ubuntu-mozilla-daily/ppa
#sudo apt-get -y update
#sudo apt-get -y dist-upgrade
#sudo apt-get -y install thunderbird-trunk thunderbird-locale-es

#latest nightly - working - https://ftp.mozilla.org/pub/thunderbird/nightly/latest-comm-central/
#example
#wget https://ftp.mozilla.org/pub/thunderbird/nightly/latest-comm-central/thunderbird-49.0a1.en-US.linux-x86_64.tar.bz2
#...

#add at boot
mkdir ~/.config/autostart
rm ~/.config/autostart/thunderbird.desktop
test -f ~/.config/autostart/thunderbird.desktop || sh -c 'echo "[Desktop Entry]
Type=Application
Exec=thunderbird
Hidden=false
X-MATE-Autostart-enabled=true
X-MATE-Autostart-Delay=50
Name[es_ES]=Thunderbird
Name=Thunderbird
Comment[es_ES]=
Comment=" >> ~/.config/autostart/thunderbird.desktop'