#!/bin/bash

#### enlightenment
##e21
#sudo add-apt-repository -y ppa:enlightenment-git/ppa
sudo add-apt-repository -y ppa:niko2040/e19
sudo apt-fast -y update
sudo apt-fast -y install enlightenment terminology
##e19
#sudo add-apt-repository -y ppa:martinx/enlightenment
#sudo apt-fast -y update
#sudo apt-fast -y install enlightenment terminology