#!/bin/bash

##### hyper
rm linux_deb linux_deb*
wget https://hyper-updates.now.sh/download/linux_deb
sudo gdebi --non-interactive linux_deb
rm linux_deb linux_deb*
sudo apt-fast -y install npm nodejs
sudo npm install -g hpm-cli