#!/bin/bash

USER=usuario

#sudo apt-fast -y install curl

#sudo curl -sSL https://get.docker.com/ | sh

#sudo docker pull nextcloud

sudo docker run --restart="always" -d -p 8081:80 -v /home/$USER/nextcloud_data:/var/www/html --name nextcloud nextcloud

#sudo docker run --restart="always" -p 0.0.0.0:8069:8069 --name odoo --link db:db -t odoo:10.0

#service

#sudo systemctl enable docker

#note: sqlite default, for mysql try another installation method