#!/bin/bash

#### vivaldi-browser

wget https://downloads.vivaldi.com/stable/vivaldi-stable_1.12.955.36-1_amd64.deb
sudo gdebi --non-interactive vivaldi-stable_*.deb
rm vivaldi-stable_*.deb

sudo apt-fast install -y chromium-codecs-ffmpeg-extra pepperflashplugin-nonfree