#!/bin/bash

#NEED RELINK

######## installpackages - Installs packages & necessary repos - script 4

#### Exec permissions
sudo chmod 777 -R ../ubuntupackages-master

#### lshw
sudo apt-fast -y install lshw-gtk

#### conky-manager
apps4/conky-manager

#### clicompanion
apps4/clicompanion

#### photoqt
apps4/photoqt

#### power-installer
apps4/power-installer

#### kdeconnect
apps4/kdeconnect

#### touchpad-indicator
apps4/touchpad-indicator

#### qllauncher
apps4/qllauncher

#### hollywood
apps4/hollywood

#### trojita
apps4/trojita

#### bum
sudo apt-fast -y install bum

#### thewindowfactory (twf)
sudo apt-fast -y install thewindowfactory

######## ONLY FOR UBUNTU WITH UNITY SURELY

#### tint2 - http://www.howtogeek.com/189819/how-to-add-a-taskbar-to-the-desktop-in-ubuntu-14.04/
sudo apt-fast -y install tint2
#at start:
#Taskbar - Tint2
#tint2
#Windows-like Taskbar

#### classicmenu-indicator_unsettings
apps4/classicmenu-indicator_unsettings

#### unity-tweak-tool
apps4/unity-tweak-tool

#### window-list_indicator-places - http://www.noobslab.com/2014/08/useful-panel-indicators-collection-for.html
apps4/window-list_indicator-places

#### indicator-systemtray-unity
apps4/indicator-systemtray-unity

#### ubuntu-tweak
apps4/ubuntu-tweak

#### gnome-tweak-tool
sudo apt-fast -y install gnome-tweak-tool

#### cpu-frequency-scaling
apps4/cpu-frequency-scaling

#### my-weather-indicator
apps4/my-weather-indicator

######## ONLY FOR KUBUNTU

#### Various
sudo apt-fast -y install muon