#!/bin/bash

#### infinality-fonts - http://www.webupd8.org/2013/06/better-font-rendering-in-linux-with.html
sudo add-apt-repository -y ppa:no1wantdthisname/ppa
#necessary / real
sudo sed -i 's/bionic/xenial/g' /etc/apt/sources.list.d/*.list
sudo apt-fast -y update
sudo apt-fast -y install fontconfig-infinality

sudo bash /etc/fonts/infinality/infctl.sh setstyle

#sudo -H gedit /etc/profile.d/infinality-settings.sh
#sudo -H pluma /etc/profile.d/infinality-settings.sh
